<?php 
	$this->headTitle(' [ eVenter ] - Como funciona ');  //titulo da página
?>

	
		
<?php echo $this->partial('partials/site_header.phtml'); ?>
	
	
<div class="ct_int">
	


	<div class="ct_content" style="display: table;">
		<div style="text-align: justify; padding: 0 30px; font-size: 16px;">
		<p>Quer sair e não sabe onde? Aqui você encontra! Reunimos todos eventos e promovemos em um único site. Tudo para facilitar a sua escolha!
		Oferecemos também promoções aos usuários e divulgação total ao parceiro.</p>
		
		<div style="float: left; margin: 30px 50px 30px 100px;">
		
		<h1 style="margin: 30px 0 10px; color: #069; font-size: 22px; ">PARA O USUÁRIO</h1>
		
			<ul>
				<li>Encontre os mais diversos eventos de sua região</li>
				<li>Avalie nossos parceiros</li>
				<li>Filtre eventos por gênero ou localização</li>
				<li>Compre ingressos e participe de promoções</li>
			</ul>
			
		</div>
		
		<div style="float: left; margin: 30px 50px 30px 30px;">
		
		<h1 style="margin: 30px 0 10px; color: #069; font-size: 22px; ">PARA O PARCEIRO</h1>
		
			<ul>
				<li>Página individual completa</li>
				<li>Divulgação de eventos por email e Redes Sociais</li>
				<li>Maior visibilização de seus eventos</li>
				<li>Venda de ingressos e promoções</li>
			</ul>		
		
		</div>
		
		</div>
	</div>
	
	
</div>

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/pages_int.css'));
?>