<div id="funcionality_ct" style="background: #F3F3F3; height: 316px; width: 100%;">
	
	<div class="title_int" style="width: 980px; font-size: 30px; color: #069; padding: 30px 0; margin: 0 auto; ">Como funciona</div>
	
	<div class="ct_page" style="width: 980px; margin: 0 auto;">
	Quer sair e não sabe onde? Aqui você encontra! Nosso objetivo é reunir todos eventos e promove-los em um único site. Oferecendo promoções aos usuários e total divulgação ao parceiro. 
	Veja como é simples! 
	
	</div>
	
	
</div>