<div class="ct_int">
	

	<div class="ct_title">
		
		<div class="ct_center">
		
			<div class="title_int">Como funciona</div>
		
		</div>
	
	</div>

	<div class="ct_content">
		<div style="text-align: justify; padding: 0 30px; font-size: 15px;">
		Quer sair e não sabe onde? Aqui você encontra! Reunimos todos eventos e promovemos em um único site. Tudo para facilitar a sua escolha!
		Oferecemos também promoções aos usuários e divulgação total ao parceiro.
		</div>
	</div>
	
	
</div>

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/pages_int.css'));
?>