<div id="contact_ct" style="background: #F3F3F3; height: 500px; width: 100%; ">
	
	<div class="title_int" style="width: 980px; font-size: 30px; color: #069; padding: 30px 0; margin: 0 auto; ">Contate-nos</div>
	
	<div class="ct_page" style="width: 980px;  margin: 0 auto;">

	<table border="0">
	  <tr>
	    <td width="482"><label for="nome">Seu nome</label></td>
	    <td width="19">&nbsp;</td>
	    <td width="393"><label for="email">Seu email</label></td>
	  </tr>
	  <tr>
	    <td><input type="text" name="nome" id="nome" class="input_cad"/></td>
	    <td>&nbsp;</td>
	    <td><input type="text" name="email" id="email" class="input_cad"/></td>
	  </tr>
	  <tr>
	    <td colspan="3">&nbsp;</td>
	  </tr>
	  <tr>
	    <td><label for="senha">Telefone</label></td>
	    <td>&nbsp;</td>
	    <td><label for="r_senha">Assunto</label></td>
	  </tr>
	  <tr>
	    <td><input type="password" name="senha" id="senha" class="input_cad"/></td>
	    <td>&nbsp;</td>
	    <td>
	        <select name="partnumber" class="estilo_select">
	        		<option></option>
	                <option value="2928" style="color: #036;" >Contato direto</option>
	                <option value="2928" style="color: #036;" >Comercial</option>
	                <option value="7382" style="color: #036;" >Dúvidas e reclamações</option>
	                
	                <option></option>
	        </select>
	    </td>
	  </tr>
	  <tr>
	    <td colspan="3">&nbsp;</td>
	  </tr>
	  <tr>
	    <td><label for="mensagem">Mensagem</label></td>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	  </tr>
	  <tr>
	    <td colspan="3">
	   	 <textarea name="mensagem" id="mensagem" cols="45" rows="5"></textarea></td>
	  </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
	  </tr>
	  <tr>
	    <td colspan="3">
	   	 	<img src="/img/btn_contato.png" class="btn_cad"/>
	    </td>
	  </tr>
	 </table>
	
	
	</div>
	
	
</div>

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/contato.css'));
?>