<?php 
	$this->headTitle(' [ eVenter ] - Política de Privacidade ');  //titulo da página
?>

		
<?php echo $this->partial('partials/site_header.phtml'); ?>
	
	
<div class="ct_int">
	


	<div class="ct_content">
		<div style="text-align: justify; padding: 0 20px; font-size: 15px;">
		A privacidade dos visitantes e usuários neste site é muito importante para nós.<br /><br />
		Em nosso site, reconhecemos a importância da privacidade e tudo faremos para a respeitar. Em  seguida apresentamos o tipo de informação pessoal que recebemos e coletamos quando você visita este site, e bem como guardamos essa informação.<br /><br />
		Nunca venderemos a sua informação para terceiros, sejam eles particulares ou empresas.<br /><br /> 
		Os registos:<br /><br />
		Tal como outros websites, coletamos e utilizamos informação contida nos registos. A informação contida nos registos inclui, o seu ISP (Internet Service Provider), o seu endereço IP (Internet Protocol), o browser que utilizou ao visitar o nosso website (ex: Firefox), o tempo da sua visita e que páginas visitou dentro do nosso website.
		<br /><br />Os Cookies e Web Beacons:<br /><br />
		Utilizamos cookies para armazenar informação, tais como as suas preferências pessoais quando visita o nosso website. Isto poderá incluir um simples pop-up, ou mesmo uma ligação em vários serviços que providenciamos (ex: fóruns). A Google faz uso do novo DART cookie para servir anúncios baseados nos seus interesses e na sua visita ao nosso blog e a outros endereços na web. Poderá optar por não utilizar o DART cookie visitando a página de anúncios do Google e o "programa de policiamento" da empresa.
		Em adição, no nosso site  também utilizamos publicidade de terceiros. Alguns destes anúncios (sponsors), poderão utilizar tecnologias como os cookies e/ou web beacons quando anunciam  no nosso website, o que fará com que esses publicitários (tal como o Google através do Google AdSense) também recebam a sua informação pessoal, como o seu ISP , o endereço IP, o seu browser, e outros.<br />
		Esta função é geralmente utilizada para "geotargeting" (ex: mostrar publicidade de NOVA YORK apenas aos leitores oriundos de Nova York) ou para apresentar publicidade direcionada a um tipo de utilizador (ex: mostrar publicidade de restaurantes/bares a um utilizador que visita regularmente portais de culinária/bebidas).
		Você pode desligar os seus cookies nas opções do seu browser, ou fazendo alterações nas ferramentas do seu Antivírus. Gostaria de lhe informar que tal procedimento poderá alterar a forma como interage com o nosso blog, ou mesmo com outros portais. Tal também poderá afetar ou mesmo não permitir que faça logins em programas, sites ou fóruns.
		</div>	
	
	</div>
	
	
</div>


<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/pages_int.css'));
?>