<?php 
	$this->headTitle(' [ eVenter ] - Termos de uso ');  //titulo da página
?>

		
<?php echo $this->partial('partials/site_header.phtml'); ?>
	
	
<style>

h2 {padding: 10px 0; font-weight: bold;}
p {padding: 10px 0;}

</style>

<div class="ct_int">
	


	<div class="ct_content">
		<div style="text-align: justify; padding: 0 30px; font-size: 15px;">
        
        <h2>ACORDO COM O USUÁRIO</h2>
        
        <p>Este Termo de Uso apresenta as "Condições Gerais" aplicáveis ao uso dos serviços oferecidos por EVENTER.COM.BR, doravante denominada "Eventer", incluindo os serviços para a aquisição com desconto de bens, produtos e serviços dentro do site www.eventer.com.br</p>
        <p>Qualquer pessoa, doravante nominada "Usuário", que pretenda utilizar os serviços do Eventer deverá aceitar este Termo de Uso, e todas as demais políticas e princípios que o regem. A UTILIZAÇÃO DO WEBSITE E SEUS SERVIÇOS PRESUME A ACEITAÇÃO DO TERMO DE USO.</p>
        <p>O Usuário deverá ler, certificar-se de haver entendido e aceitar todas as condições estabelecidas no Termo de Uso, no ato do acesso ao Website, assim como nos demais documentos incorporados aos mesmos por referência, antes de seu cadastro como Usuário do Eventer.</p>
        <p>O usuário pode entrar em contato com o Eventer através do canal "FALE CONOSCO" ou do link <a href="http://www.eventer.com.br/site/contato">http://www.eventer.com.br/site/contato</a>.</p>
        <p>O usuário concorda que, para ficar ciente de informações importantes relativas a sua conta e manter a comunicação com a empresa, o endereço de e-mail cadastrado será o canal de comunicação utilizado pelo Eventer. </p>

        <h2>1. OBJETO.</h2>
        <p>1.1 Os serviços objeto do presente Termo de Uso consistem em colocar a disposição dos Usuários, direta ou indiretamente cadastrados em seu website, 
        eventos e ofertas periódicas para aquisição com desconto de produtos e/ou serviços de empresas parceiras do Eventer.</p>
        <p>1.2 O Eventer não é o proprietário dos produtos e/ou serviços ofertados pelos Parceiros, não guarda a posse deles e não realiza Ofertas em seu nome, entretanto, fica à disposição, através de seus canais de atendimento ao Usuário, para intermediar qualquer comunicação necessária com o Parceiro e tomar as providências necessárias para a solução de eventual transtorno.</p>


        <h2>2 CADASTRO NO WEBSITE.</h2>
        <p>2.1 Os serviços do Eventer estão disponíveis apenas para as pessoas que tenham capacidade legal para contratá-los. Não podem utilizá-los, assim, pessoas que não gozem dessa capacidade, ou pessoas que tenham sido inabilitadas do Eventer temporáriamente ou definitivamente.</p>
        <p>2.2 Em nenhuma hipótese serão permitidas a cessão, venda, aluguel ou outra forma de transferência da conta. Também não se permitirá a manutenção de mais de um cadastro por uma mesma pessoa, ou ainda a criação de novos cadastros por pessoas cujos cadastros originais tenham sido cancelados por infrações às políticas do Eventer. Em todos estes casos, o Eventer se reserva no direito de excluir todas as contas existentes do Usuário infrator.</p>
        <p>2.3 Somente será confirmado o cadastramento do interessado que preencher todos os campos do cadastro. O futuro Usuário deverá completá-lo com informações exatas, precisas e verdadeiras, e assume o compromisso de atualizar os dados pessoais sempre que neles ocorrer alguma alteração.</p>
        <p>2.4 O Eventer não se responsabiliza pela correção dos dados pessoais inseridos por seus Usuários. Os Usuários garantem e respondem, em qualquer caso, pela veracidade, exatidão e autenticidade dos dados pessoais cadastrados.</p>
        <p>2.5 O Eventer se reserva o direito de utilizar todos os meios válidos e possíveis para identificar seus Usuários, bem como de solicitar dados adicionais e documento de identificação válido que estime ser pertinente, a fim de conferir os dados pessoais informados.</p>
        <p>2.6 Caso exista a necessidade, por qualquer motivo, de conferência dos dados cadastrais de um Usuário e se constate haver dados incorretos ou inverídicos, ou ainda caso o Usuário se furte ou negue a enviar os documentos requeridos para conferência, o Eventer poderá cancelar, definitivamente ou não, o cadastro do Usuário, sem prejuízo de outras medidas que entender necessárias e oportunas.</p>
        <p>2.7 O Usuário acessará sua conta através de e-mail e senha e compromete-se a não informar a terceiros esses dados, responsabilizando-se integralmente pelo uso que deles seja feito.</p>
        <p>2.8 O Usuário compromete-se a notificar o Eventer imediatamente, e através de meio seguro, a respeito de qualquer uso não autorizado de sua conta, bem como o acesso não autorizado por terceiros à mesma. O Usuário será o único responsável pelas operações efetuadas em sua conta, uma vez que o acesso à mesma só será possível mediante a aposição da senha, cujo conhecimento é exclusivo do Usuário.</p>


        <h2>3. MODIFICAÇÕES DO TERMO DE USO.</h2>
        <p>3.1 O Eventer poderá alterar, a qualquer tempo, este Termo de Uso, visando seu aprimoramento e melhoria dos serviços prestados. O novo Termo de Uso entrará em vigor a partir de sua publicação no website. No prazo de 24 (vinte e quatro) horas contadas a partir da publicação das modificações, o Usuário deverá comunicar por e-mail caso não concorde com o Termo de Uso alterado. Nesse caso, o vínculo contratual deixará de existir, desde que não haja contas ou dívidas em aberto em nome do Usuário. Não havendo manifestação no prazo estipulado, entender-se-á que o Usuário aceitou tacitamente o novo Termo de Uso e o contrato continuará vinculando as partes.</p>

        <h2>4. PRIVACIDADE DA INFORMAÇÃO.</h2>
        <p>4.1 O Eventer tomará todas as medidas possíveis para manter a confidencialidade e a segurança descritas nesta cláusula, porém não responderá por prejuízo que possa ser derivado da violação dessas medidas por parte de terceiros que utilizem as redes públicas ou a internet, subvertendo os sistemas de segurança para acessar as informações de Usuários.</p>
        <p>4.2 Para obter maiores informações sobre a Política de Privacidade do Eventer, o Usuário pode acessar o link <a href="http://eventer.com.br/site/politica-de-privacidade">http://acao.dev/site/politica-de-privacidade</a>.</p>

        <h2>5. OBRIGAÇÕES DOS USUÁRIOS.</h2>
        <p>5.1 Os Usuários interessados nas Ofertas anunciadas pelo Eventer devem realizar as aquisições e pagamento durante o Período de Publicação. A Publicação da Oferta encerra-se quando expirado o prazo definido pelo Eventer ou quando esgotar a quantidade do produto e/ou serviço oferecido pelo Parceiro.</p>
        <p>5.2 O Usuário adquirente, após manifestar-se pela Aquisição da Oferta, obriga-se a adquirir a Oferta no caso de sua Validação, bem como a seu pagamento. A Oferta de Compra é irrevogável, nos termos dos artigos 427 e 429 do Código Civil, ressalvadas circunstâncias excepcionais.</p>

        <h2>6. VIOLAÇÃO NO SISTEMA OU BASE DE DADOS.</h2>
        <p>6.1 Não é permitida a utilização de nenhum dispositivo, software, ou outro recurso que venha a interferir nas atividades e operações do Eventer, bem como nas publicações de Oferta, descrições, contas ou seus bancos de dados. Qualquer intromissão, tentativa de, ou atividade que viole ou contrarie as leis de direito de propriedade intelectual e/ou as proibições estipuladas neste Termo de Uso, tornarão o responsável passível das ações legais pertinentes, bem como das sanções aqui previstas, sendo ainda responsável pelas indenizações por eventuais danos causados.</p>

        <h2>7. SANÇÕES.</h2>
        <p>7.1 Sem prejuízo de outras medidas, o Eventer poderá advertir, suspender ou cancelar, temporária ou definitivamente, a conta de um Usuário a qualquer tempo, 
        e iniciar as ações legais cabíveis se: 
        <br />a) o Usuário que não cumprir qualquer dispositivo deste Termo de Uso; 
        <br />b) se descumprir com seus deveres de Usuário; 
        <br />c) se praticar atos fraudulentos ou dolosos; 
        <br />d) se não puder ser verificada a identidade do Usuário ou qualquer informação fornecida por ele esteja incorreta; 
        <br />e) se o Eventer entender que os anúncios ou qualquer atitude do Usuário tenham causado algum dano a terceiros ou ao próprio 
        Eventer ou tenham a potencialidade de assim o fazer. 
        <br />Nos casos de inabilitação do cadastro do Usuário, todas as Aquisições de Ofertas ativas serão automaticamente canceladas. O Eventer reserva-se o direito de, a qualquer momento e a seu exclusivo critério, solicitar o envio de documentação pessoal.</p>

        <h2>8. RESPONSABILIDADES DE FUNCIONAMENTO.</h2>
        <p>8.1 Tendo em vista, ainda, a impossibilidade de funcionamento integral e ininterrupto de qualquer sistema de telecomunicação ou de informática, inclusive em razão da dependência de serviços de telecomunicações prestados por terceiros, o Eventer não garante a prestação do serviço de forma ininterrupta e/ou isenta de erros. Eventualmente, o sistema poderá não estar disponível por motivos técnicos ou falhas da internet, ou por qualquer outro evento fortuito ou de força maior alheio ao controle do Eventer.</p>

        <h2>9. PROPRIEDADE INTELECTUAL.</h2>
        <p>9.1 O uso comercial da expressão "Eventer" como marca, nome de domínio, bem como os conteúdos das telas relativas aos serviços do Eventer assim como os programas, bancos de dados, redes e arquivos, que permitem que o Usuário acesse e use sua conta, são de propriedade do Eventer e estão protegidos pelas leis e tratados internacionais de direito autoral, marcas, patentes, modelos e desenhos industriais. O uso indevido e a reprodução total ou parcial dos referidos conteúdos são proibidos, salvo a autorização expressa do Eventer.</p>
        <p>9.2 O Eventer não será responsável pelos conteúdos, práticas e serviços ofertados em outros sites que não sejam de propriedade ou operados por si, ainda que exista independentemente do motivo, link para os mesmos no website Eventer. A presença de links para outros sites não implica relação de sociedade, de supervisão, de cumplicidade ou solidariedade do Eventer para com esses sites e seus conteúdos.</p>
        
        <h2>10. INDENIZAÇÃO.</h2>
        <p>10.1 O Usuário indenizará o Eventer, suas filiais, empresas controladas ou controladoras, diretores, administradores, colaboradores, representantes e empregados por qualquer demanda promovida por outros usuários ou terceiros decorrentes de suas atividades no site ou por seu descumprimento dos Termos de Uso ou pela violação de qualquer lei ou direitos de terceiros, incluindo honorários de advogados.</p>

        <p>Não obstante a existência do presente Termo de Uso, a relação entre o Eventer e o usuário é regida pelas leis brasileiras, em especial pelo Código de Defesa do Consumidor.</p>
		</div>
	</div>
	
	
</div>

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/pages_int.css'));
?>