<?php 
	$parceiro = $this->parceiro;
?>

<table width="923" border="0" style="margin: 0 auto;">
	  <tr>
	    <td height="22"><div class="ct_info"><span class="txt_contact"><?php echo $parceiro->telefone ?></span></div></td>
	    <td width="29" rowspan="9">&nbsp;</td>
	    <td><div class="ct_info"><span class="txt_contact">contato@balada.com.br</span></div></td>
  </tr>
	  <tr>
	    <td height="22">&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td width="429" height="22"><label for="nome">Seu nome</label></td>
	    <td width="451"><label for="email">Seu email</label></td>
      </tr>
	  <tr>
	    <td><input type="text" name="nome" id="nome" class="input_z"/></td>
	    <td><input type="text" name="email" id="email" class="input_z"/></td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td><label for="senha">Telefone</label></td>
	    <td><label for="r_senha">Assunto</label></td>
      </tr>
	  <tr>
	    <td><input type="text" name="phone" id="phone" class="input_z"/></td>
	    <td>
			<input type="text" name="assunto" id="assunto" class="input_z"/>
	    </td>
      </tr>
	  <tr>
	    <td>&nbsp;</td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td><label for="mensagem">Mensagem</label></td>
	    <td>&nbsp;</td>
      </tr>
	  <tr>
	    <td colspan="3"><textarea name="mensagem" id="mensagem" cols="45" rows="5"></textarea></td>
      </tr>
	  <tr>
	    <td colspan="3" height="3">&nbsp;</td>
      </tr>
	  <tr>
	    <td colspan="3"><img src="/img/btn_contato.png" class="btn_cad" style="float: right;"/></td>
      </tr>
     </table>
	
<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/parceiro_contact.css'));
?>