

<?php 

$evento = $this->evento;
$parceiro = $this->parceiro;

$event = array();
$event['id'] = $evento->id;
$event['nome'] = $evento->nome;
$event['url'] =  $this->serverUrl() .'/' . $parceiro->url_amigavel . '/' . $evento->url_amigavel;
$event['imagem']  = $this->serverUrl() ."/img/eventos/".$evento->capa;
$event['data'] =  date('d/m/Y', strtotime( $evento->realizacao));
$event['descricao'] =  $evento->descricao;
$events[] = $event;

$this->headTitle($evento->nome . ' - ' . date('d/m/Y', strtotime( $evento->realizacao)) . ' - ' . $parceiro->nome . ' [ eVenter ] ');  //titulo da página
$this->headMeta()->setProperty('og:title', $evento->nome . ' - ' . date('d/m/Y', strtotime( $evento->realizacao)) . ' - ' . $parceiro->nome . ' [ eVenter ] ');
$this->headMeta()->setProperty('og:image', $this->serverUrl() .'/img/eventos/'.$evento->capa);
$this->headMeta()->setProperty('og:site_name', 'eVenter - Entradas para o seu evento');
$this->headMeta()->setProperty('og:description', $evento->descricao);
$this->headMeta()->setProperty('og:url', $event['url']);
$this->headMeta()->setProperty('og:type', 'eventer_social:event');
$this->headMeta()->setProperty('fb:app_id', '240996152682246');


?>


<script type="text/javascript">
var events = <?php echo json_encode($events); ?>;
</script>


<div class="evento_wrap">

	<div class="evento_content">
	
		<div class="evento_flyer">
		
			<?php if(count($evento->cortesias) > 0) :  //verifica se existem cortesias?>
				<div class="evento_promo"><img src="/img/evento_flyer_promo.png" /></div>
				<?php else:?>
				<div class="evento_promo"><img src="/img/evento_flyer_no_promo.png" /></div>
			<?php endif; ?>
			
			
			<div class="evento_flyer_mold">
				<div class="evento_flyer_img">
					<img alt="<?php echo $evento->nome ?>" src="/img/eventos/<?php echo $evento->capa?> "/>
				</div>
			</div>
			<div class="ct_icos">
				<ul>
					<li style="float: left; margin-right: 2px; cursor: pointer;" onclick='share("<?php echo $evento->id ?>");' >
						<img src="/img/btn_events_facebook.png">
						
					</li>
					<?php /*
					<li style="float: left; cursor: pointer;">
						<img src="/img/btn_events_mail.png">
					</li>
					*/ ?>
					<li class="li_zoom" rel="flyer_<?php echo $evento->id ?>" style="float: right; cursor: pointer;">
						<img src="/img/btn_events_zoom.png">
					</li>
				</ul>
			</div>
		</div>
		
		<div class="evento_flyer_zoom" id="flyer_<?php echo $evento->id ?>">
				<img alt="<?php echo $evento->nome ?>" src="/img/eventos/<?php echo $evento->capa?> "/>
		</div>
		
		<div class="evento_description">
		
			<div class="evento_description_label">
				evento:
			</div>
			<div class="evento_description_content">
					<?php echo $evento->nome ?>
			</div>
			
			<div class="evento_description_total">
			<span>(<?php echo implode(', ', $evento->generos); ?>)</span>
			<?php echo $evento->descricao ?>
			</div>
		


		</div>
		
		<div class="evento_date">
				<?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?>				
		</div>
		
	
	</div>



	<?php if(count($evento->cortesias) > 0) :  //verifica se existem cortesias?>
		<div class="evento_promotions" id="showpromo_<?php echo $evento->id ?>">
			<table>
				<thead>
				  <tr>
				    <th>Tipo</th>
				    <th>Disponíveis</th>
				    <th>Valor</th>
				    <th class="th_empty"></th>
				  </tr>
				</thead>
				<tbody>
			  	<?php foreach ($evento->cortesias as $cortesias) : ?>
			  	
				  <tr>
				    <td><?php echo $cortesias->nome ?></td>
				    <td>
				    	<span class="max_destak"><?php echo $cortesias->disponivel ?></span> de <span class="min_destak"><?php echo $cortesias->qtd ?></span>
				    </td>
				    <td>
				    	de <span class="min_destak">R$<?php echo $cortesias->valor_original ?></span> por <span class="max_destak">R$<?php echo $cortesias->valor ?></span>
				    </td>
				    <td>
				    	<div class="cortesia_euquero" id="cortesia_<?php echo $cortesias->id ?>" >
				    		Eu quero
				    	</div>
				    </td>
				  </tr>
				<?php endforeach; ?>
				
				</tbody>
			</table>
		</div>
	<?php endif;?>

</div>



<!-- #START DIALOG CORTESIAS -->

<div id="dialog_cortesia"></div><!-- Div modal CONVERTER CORTESIA -->


<?php 
//$this->headLink()->prependStylesheet($this->baseUrl('/css/.css'));
$this->headScript()->prependFile($this->baseUrl('/js/parceiro_evento.js'));
?>	

<style>
div.evento_wrap
{
	margin-bottom: 70px;
}

div.evento_promotions
{
	width: 928px;
	margin-top: 40px;
}


div.evento_promotions div.cortesia_euquero
{
	cursor: pointer;
	background: transparent url("/img/evento_promotions_iwant.png") 10px center no-repeat;
	text-transform: uppercase;
}



div.evento_promotions table
{
	width: 928px;
	border: 1px dashed #CCCCCC;
	border-spacing: 0;
	background: transparent url("/img/evento_promotions_table_thead.png") top repeat-x;
	
}

div.evento_promotions table .max_destak
{
	color: #00CCFF;
	font-size: 25px;
}
div.evento_promotions table .min_destak
{
	color: #00CCFF;
	font-size: 15px;
}

div.evento_promotions table tbody
{
	background-color: #F2F2F2;	
	border: 1px dashed #CCC;
	border-top: 0px;
}

div.evento_promotions table tbody tr
{
	border-top: 1px solid #FFF;
}

div.evento_promotions table tbody tr:HOVER
{
	background-color: #F6F6F6;
}

div.evento_promotions table tbody td
{
	font-size: 15px;
	line-height: 46px;
	text-align: center;
}


div.evento_promotions table thead th
{
	line-height: 48px;
	font-size: 15px;
/* 	height: 48px; */
	text-transform: uppercase;
	text-align: center;
	background: transparent url("/img/evento_promotions_table_thead_icon.png") center 35px no-repeat;
}


div.evento_promotions table thead th.th_empty
{
	background-image: none;
}



div.evento_content
{
	background: transparent url("/img/evento_container_back.png");
	position: relative;
}
div.evento_content div.evento_flyer
{
	position: relative;
	background: transparent url("/img/evento_flyer_back.png");
	width: 297px;
	height: 350px;
}

div.evento_content div.evento_flyer div.evento_promo
{
	position: absolute;
	left: -7px;
	top: 10px;
}
div.evento_content div.evento_flyer div.evento_flyer_mold
{
	width: 258px;
	height: 258px;
	background: transparent url("/img/evento_flyer_mold_parceiro.png") center center no-repeat;
	position: absolute;
	left: 18px;
	top: 66px;
}

div.evento_content div.evento_flyer div.evento_flyer_mold div.evento_flyer_img
{
	width: 248px;
	height: 248px;
	padding-top: 6px;
	margin: 0 auto;
}
div.evento_content div.evento_flyer div.evento_flyer_mold div.evento_flyer_img img
{
	width: 248px;
	height: 248px;
	margin: 0 auto;
}

div.evento_content div.evento_flyer div.ct_icos
	{
width: 296px;
display: table;
bottom: -4px;
position: absolute;
}

div.evento_content div.evento_flyer_zoom
{
	display: none;
}


div.evento_content div.evento_description
{
	position: absolute;
	top: 40px;
	left: 320px;
}
div.evento_content div.evento_description div.evento_description_label
{
	color: #999999;
	font-size: 18px;
	float: left;
	width: 60px;
	text-align: right;
}
div.evento_content div.evento_description div.evento_description_content
{
	font-size: 22px;
	color: #000;
	white-space: nowrap;
	padding-left: 70px;
}
div.evento_content div.evento_description div.evento_description_total
{
	background-color: #F0F0F0;
	height: 200px;
	overflow: auto;
	margin: 30px 25px 10px 0;
	padding: 25px;
	width: 530px;
}

div.evento_content div.evento_date 
{
	font-size: 30px;
	position: absolute;
	right: 30px;
	top: 38px;;
}
</style>
