<?php 
$parceiro = $this->parceiro;

$this->headTitle($parceiro->nome . ' [ eVenter ] ');  //titulo da página
$this->headMeta()->setProperty('og:title', $parceiro->nome . ' [ eVenter ] ');
$this->headMeta()->appendProperty('og:image', $this->serverUrl() .'/img/parceiros/'.$parceiro->foto);
$this->headMeta()->setProperty('og:description', strip_tags($parceiro->descricao));
$this->headMeta()->setProperty('og:url', $this->serverUrl() .'/' . $parceiro->url_amigavel);



?>


<?php if(count($this->parceiro->fotos) > 0)  : ?>

<div id="fotos" style="width: 900px; height: 500px; margin: 0 auto; text-align: center; border: 1px solid red;">
	<?php foreach ($this->parceiro->fotos as $fotos) :?>
			<a href="/img/parceiros/<?php echo $fotos->url ?>"><img src="/img/parceiros/150px/<?php echo $fotos->url ?>" /></a>
			
			
		<?php 
			$this->headMeta()->appendProperty('og:image', $this->serverUrl() .'/img/parceiros/'.$fotos->url);
		?>
	<?php endforeach; ?>
</div>
	<?php 
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/galleria.classic.css'));
	
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/galleria-1.2.9.min.js'))
		->appendFile($this->baseUrl('/js/galleria.classic.min.js'))
		->appendFile($this->baseUrl('/js/parceiro_fotos.js'));
	?>	

<?php else : ?>

		<div class="container_content_msg">	
			Nenhuma foto cadastrada para este local
		</div>

<?php endif; ?>