<?php

$parceiro = $this->parceiro;


$this->headTitle($parceiro->nome . ' [ eVenter ] ');  //titulo da página
$this->headMeta()->setProperty('og:title', $parceiro->nome . ' [ eVenter ] ');
$this->headMeta()->setProperty('og:image', $this->serverUrl() .'/img/parceiros/'.$parceiro->foto);
$this->headMeta()->setProperty('og:site_name', 'eVenter - Entradas para o seu evento');
$this->headMeta()->setProperty('og:description', $parceiro->descricao);
$this->headMeta()->setProperty('og:url', $this->serverUrl() .'/' . $this->parceiro->url_amigavel);
$this->headMeta()->setProperty('og:type', 'eventer_social:event');
$this->headMeta()->setProperty('fb:app_id', '240996152682246');

?>

<div class="wrap" style="display: table; width: 930px;">

	<div class="wrapLeft" style="width: 626px; display: table; float: left;">

		<div class="desc_parc">
		
			<p style="font-weight: bold; padding: 10px 0; font-size: 16px;">DESCRIÇÂO DO LOCAL</p>
			<p>Uma casa repleta de mulheres dispidas e loucas por amor.</p>
		
		</div>
		
		<div class="commentsFb" style="display: table; margin: 60px 0 0 0; background: #fbfbfb;">
		
			<div class="fb-comments" data-href="<?php echo $this->serverUrl() .'/' . $this->parceiro->url_amigavel ?>" data-width="600" data-num-posts="3"></div>
		
		
		</div>
	
	</div>
	
	<div class="wrapRight" style="width: 302px; float: left;">

		
		<div class="form_parc" style="padding: 0 10px;">
		
			<p style="font-weight: bold; padding: 10px 0; font-size: 16px;">CONTATO</p>
			<?php echo $this->form?>
		
		</div>	
		
	
	</div>



</div>

<style>

div.wrap div.wrapRight div.form_parc input[type="text"]{width: 200px; padding: 5px 10px; outline: 0; border: 1px solid #CCC; border-radius: 2px;}
div.wrap div.wrapRight div.form_parc textarea{width: 270px; padding: 5px 10px; outline: 0; border: 1px solid #CCC;}
div.wrap div.wrapRight div.form_parc input[type="submit"]
	{
	width: 200px; padding: 8px 10px; outline: 0; border: 1px solid #09F; float: right; border-radius: 2px;
	background: #7abcff; /* Old browsers */
	/* IE9 SVG, needs conditional override of 'filter' to 'none' */
	background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzdhYmNmZiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjQ0JSIgc3RvcC1jb2xvcj0iIzYwYWJmOCIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiM0MDk2ZWUiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
	background: -moz-linear-gradient(top,  #7abcff 0%, #60abf8 44%, #4096ee 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#7abcff), color-stop(44%,#60abf8), color-stop(100%,#4096ee)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top,  #7abcff 0%,#60abf8 44%,#4096ee 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top,  #7abcff 0%,#60abf8 44%,#4096ee 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(top,  #7abcff 0%,#60abf8 44%,#4096ee 100%); /* IE10+ */
	background: linear-gradient(to bottom,  #7abcff 0%,#60abf8 44%,#4096ee 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#7abcff', endColorstr='#4096ee',GradientType=0 ); /* IE6-8 */
	
}

</style>