<?php

$parceiro = $this->parceiro;


$this->headTitle($parceiro->nome . ' [ eVenter ] ');  //titulo da página
$this->headMeta()->setProperty('og:title', $parceiro->nome . ' [ eVenter ] ');
$this->headMeta()->setProperty('og:image', $this->serverUrl() .'/img/parceiros/'.$parceiro->foto);
$this->headMeta()->setProperty('og:site_name', 'eVenter - Entradas para o seu evento');
$this->headMeta()->setProperty('og:description', $parceiro->descricao);
$this->headMeta()->setProperty('og:url', $this->serverUrl() .'/' . $this->parceiro->url_amigavel);
$this->headMeta()->setProperty('og:type', 'eventer_social:event');
$this->headMeta()->setProperty('fb:app_id', '240996152682246');

?>

<div class="wrap">

	<div class="wrapLeft">

		<div class="desc_parc">
			
			<p class="title_homeP">DESCRIÇÂO DO LOCAL</p>
			<p><?php echo $parceiro->descricao ?></p>
		
		</div>
		
		<div class="commentsFb">
		
			<div class="fb-comments" data-href="<?php echo $this->serverUrl() .'/' . $this->parceiro->url_amigavel ?>" data-width="600" data-num-posts="3"></div>
		
		
		</div>
	
	</div>
	
	<div class="wrapRight">

		
		<div class="form_parc">
		
			<p class="title_homeP">CONTATO</p>
			<?php echo $this->form?>
		
		</div>	
		
	
	</div>

</div>


<?php
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/parceiro_home.css'));
?>
