
<?php $local = $this->parceiro->local; ?>

<div style="border: 1px solid #55C8FF ;font-size: 20px; padding: 30px 20px; width: 860px; margin: 0 auto; margin-bottom: 20px; 

background: #ddf2ff; /* Old browsers */
/* IE9 SVG, needs conditional override of 'filter' to 'none' */
background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIyJSIgc3RvcC1jb2xvcj0iI2RkZjJmZiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNjZmU0ZjciIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
background: -moz-linear-gradient(top,  #ddf2ff 2%, #cfe4f7 100%); /* FF3.6+ */
background: -webkit-gradient(linear, left top, left bottom, color-stop(2%,#ddf2ff), color-stop(100%,#cfe4f7)); /* Chrome,Safari4+ */
background: -webkit-linear-gradient(top,  #ddf2ff 2%,#cfe4f7 100%); /* Chrome10+,Safari5.1+ */
background: -o-linear-gradient(top,  #ddf2ff 2%,#cfe4f7 100%); /* Opera 11.10+ */
background: -ms-linear-gradient(top,  #ddf2ff 2%,#cfe4f7 100%); /* IE10+ */
background: linear-gradient(to bottom,  #ddf2ff 2%,#cfe4f7 100%); /* W3C */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ddf2ff', endColorstr='#cfe4f7',GradientType=0 ); /* IE6-8 */



"><?php echo $local->rua?> - <?php echo $local->numero?> - <?php echo $local->cidade->nome?> - <?php echo $local->cidade->estado->nome?></div>

<div class="location-view">
				
				
			 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

		    <script>
		    
		    var geocoder;
		    var map;
		    var marker;
		    
			function carregarNoMapa() {
		    	
		    	var address = "<?php echo $local->rua .", ". $local->numero ." - ". $local->cidade->nome .", ". $local->cidade->estado->nome; ?>";
		        geocoder.geocode({ 'address': address + ', Brasil', 'region': 'BR' }, function (results, status) {
		            if (status == google.maps.GeocoderStatus.OK) {
		                if (results[0]) {
		                    var latitude = results[0].geometry.location.lat();
		                    var longitude = results[0].geometry.location.lng();
		                    var location = new google.maps.LatLng(latitude, longitude);
		                    marker.setPosition(location);
		                    map.setCenter(location);
		                    map.setZoom(15);
		                }
		            }
		        });
		    }
		     
		    function initialize() {
		        var latlng = new google.maps.LatLng(-27.59449,-48.613901);
		        var options = {
		            zoom: 5,
		            center: latlng,
		            mapTypeId: google.maps.MapTypeId.ROADMAP
		        };
		     
		        map = new google.maps.Map(document.getElementById("map"), options);
		        geocoder = new google.maps.Geocoder();
		        marker = new google.maps.Marker({
		            map: map,
		            draggable: true,
		        });
		     
		        marker.setPosition(latlng);
		        carregarNoMapa();
		    }

		    google.maps.event.addDomListener(window, 'load', initialize);
		    </script>
				
		   <div id="map" style="width: 900px; height: 500px; margin: 0 auto; text-align: center; border: 1px solid #55C8FF;"></div>
				
	</div>