
<?php $local = $this->parceiro->local; ?>

<div style="border: 4px solid #fbfbfb; font-size: 20px; padding: 20px 20px; width: 860px; margin: 0 auto; margin-bottom: 20px; background: #fbfbfb;"><?php echo $local->rua?> | <?php echo $local->numero?> | <?php echo $local->cidade->nome?> | <?php echo $local->cidade->estado->nome?></div>

<div class="location-view">
				
				
			 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

		    <script>
		    
		    var geocoder;
		    var map;
		    var marker;
		    
			function carregarNoMapa() {
		    	
		    	var address = "<?php echo $local->rua .", ". $local->numero ." - ". $local->cidade->nome .", ". $local->cidade->estado->nome; ?>";
		        geocoder.geocode({ 'address': address + ', Brasil', 'region': 'BR' }, function (results, status) {
		            if (status == google.maps.GeocoderStatus.OK) {
		                if (results[0]) {
		                    var latitude = results[0].geometry.location.lat();
		                    var longitude = results[0].geometry.location.lng();
		                    var location = new google.maps.LatLng(latitude, longitude);
		                    marker.setPosition(location);
		                    map.setCenter(location);
		                    map.setZoom(15);
		                }
		            }
		        });
		    }
		     
		    function initialize() {
		        var latlng = new google.maps.LatLng(-27.59449,-48.613901);
		        var options = {
		            zoom: 5,
		            center: latlng,
		            mapTypeId: google.maps.MapTypeId.ROADMAP
		        };
		     
		        map = new google.maps.Map(document.getElementById("map"), options);
		        geocoder = new google.maps.Geocoder();
		        marker = new google.maps.Marker({
		            map: map,
		            draggable: true,
		        });
		     
		        marker.setPosition(latlng);
		        carregarNoMapa();
		    }

		    google.maps.event.addDomListener(window, 'load', initialize);
		    </script>
				
		   <div id="map" style="width: 900px; height: 500px; margin: 0 auto; text-align: center; border: 1px solid #FFF;"></div>
				
	</div>