
<div id="initial" style="background: #E6E6E6;">
	<div id="ct_initial" style="border: 1px solid #CCC; width: 980px; margin: 0 auto; padding: 80px 0;">
	
		<div id="ct_logo" style="border: 1px solid red; width: 300px; height: 200px; margin: 0 auto; margin-bottom: 30px;"></div>
		<div id="ct_location" style="border-top: 1px solid #fbfbfb; margin: 0 auto; padding: 20px 10px; background: #CCC;">
			<div id="location" style="float: left;">Informe sua localidade: Selecione</div>
			<div id="ct_alternate" style="float: right;">Não encontrou sua cidade?</div>
		</div>
		<div id="ct_cities" style="border-top: 1px solid #fbfbfb; margin: 0 auto; padding: 20px 10px; background: #CCC; display: none;">
			Exibe cidades
		</div>
	
	</div>
</div>	
