
<?php foreach ($this->eventos as $evento): ?>

<pre>
<?php //print_r($evento)?>
</pre>

<div class="ct_event">
	<div class="event">
		
		<div class="ct_left_e">
			<div class="ct_flyer_e">
				Flyer
			</div>
			<div class="ct_sociais_e">
				<ul>
					<li class="social_ico_e"><img src="/img/btn_like.png" /></li>
					<li class="social_ico_e"><img src="/img/btn_twitter.png" /></li>
					<li class="social_ico_e"><img src="/img/btn_mail.png" /></li>
				</ul>
			</div>
		</div>
		
		<div class="ct_right_e">
		
			<div class="ct_event_date">
				<span class="event_name">Evento: <?php echo $evento->nome ?></span>
				<span class="event_date">Data: <?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?></span>	
			</div>
			
			<div class="ct_event_local">
				<span class="event_local">
				Local: <a href="	<?php echo $this->url(array('id' => $evento->parceiro->id, 'nome' => $evento->parceiro->nome), 'parceiro') ?> ">
							<?php echo $evento->parceiro->nome ?>
					   </a>
				</span>
				<span class="parc_aval">
					<img src="/img/event_aval.png"/>
				</span>	
			</div>

			<div class="ct_btn_event_desc">
				<span class="btn_desc">
				+ ver detalhes 
				</span>	
			</div>

			<a href="	<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?> ">
			<div class="btn_go_event">
				Ir para página do evento
			</div>
			</a>
		
		</div>
	
	</div>
	
	<div class="promo_event" style="width: 620px; border: 1px solid red; height: 56px;"></div>

</div>

	<h5>id:<?php echo $evento->id ?>  Nome: <?php echo $evento->nome ?></h5>
	
	Link: 
	<a href="	<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?> ">
		<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?>
	</a>
	<p>
	Realização:	<?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?>
	</p>
	<p>
	Descrição: <?php echo $evento->descricao ?>
	</p>
	<p>
	Parceiro:
		<a href="	<?php echo $this->url(array('id' => $evento->parceiro->id, 'nome' => $evento->parceiro->nome), 'parceiro') ?> ">
		<?php echo $evento->parceiro->nome ?>
		</a>
	</p>
	<p>
	Descrição do parceiro: <?php echo $evento->parceiro->descricao ?>
	</p>
	<p>
	Foto do parceiro: <?php echo $evento->parceiro->foto ?>
	</p>
	
	<p>
	<?php  echo $evento->parceiro->local->rua ?>, <?php echo $evento->parceiro->local->numero ?> <?php echo $evento->parceiro->local->complemento ?>
	<?php  echo $evento->parceiro->local->cidade->nome ?>-<?php echo $evento->parceiro->local->cidade->estado->sigla ?>
	</p>
	
	<?php //if(count($evento->cortesias) > 0) :?>
	
		<h2>Cortesias</h2>
		<?php foreach ($evento->cortesias as $cortesias) : ?>
			Ingresso: <?php echo $cortesias->nome ?> (<?php echo $cortesias->descricao ?>)
			Disponível: <?php echo $cortesias->disponivel ?>
			Valor: <?php echo $cortesias->valor ?>
			<hr />
		<?php endforeach; ?>
	
	<?php //endif;?>
	
	
	<hr />
<?php	endforeach;  ?>





<h2>Destaques</h2>
<?php foreach ($this->destaques as $destaques): ?>
	Data: <?php echo date('d/m/Y', strtotime( $destaques->realizacao)) ?>
	Nome: <?php echo $destaques->nome ?>
	Local: <?php echo $destaques->parceiro->nome ?>
	<br>
	<hr>
<?php endforeach;  ?>



<?php 
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/eventos.js'));

	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/eventos.css'));
?>
