
<?php foreach ($this->eventos as $evento): ?>

<pre>
<?php //print_r($evento)?>
</pre>

<div class="ct_left">
	<div class="ct_event">
		
		<div class="banner_promo"></div>
		
		<div class="event">
		
		<!-- #FLYER E SOCIAIS -->
			
			<div class="ct_left_e">
				<div class="ct_flyer_e">
					<img alt="<?php echo $evento->nome ?>" src="/img/eventos/<?php echo $evento->capa?> "/>
				</div>
				<div class="ct_sociais_e">
					<ul>
						<li class="social_ico_e"><img src="/img/btn_like.png" /></li>
						<li class="social_ico_e"><img src="/img/btn_twitter.png" /></li>
						<li class="social_ico_e"><img src="/img/btn_mail.png" /></li>
					</ul>
				</div>
			</div>
			
			<!-- #START NOME EVENTO/DATA/LOCAL/AVALIAÇÃO -->
			
			<div class="ct_right_e">
			
				<div class="ct_event_date">
					<span class="event_name">Evento: <?php echo $evento->nome ?></span>
					<span class="event_date">Data: <?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?></span>	
				</div>
				
				<div class="ct_event_local">
					<span class="event_local">
						Local: <a href="	<?php echo $this->url(array('id' => $evento->parceiro->id, 'nome' => $evento->parceiro->nome), 'parceiro') ?> ">
									<?php echo $evento->parceiro->nome ?>
							   </a>
						<span class="parc_aval">
							<img src="/img/event_aval.png"/>
						</span>	
					</span>
	
				</div>
				
				
				<div class="ct_btns">
	
					<span class="btn_desc">
						<a href="">
							<div class="show_details_event" id="btndetails_<?php echo $evento->id ?>">
								+detalhes
							</div>
						</a>
					</span>
	
	
					<span class="btn_bonus">
						<a href="">
							<div class="show_details_bonus" id="btnbonus_<?php echo $evento->id ?>">
								+bonus <span class="bonus_count"><?php echo count($evento->cortesias) ?></span>
							</div>
						</a>
					</span>
	
				
				</div>
	
				<a href="	<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?> ">
					<div class="btn_go_event">
						Ir para página do evento
					</div>
				</a>
			
			</div>
			
			<!-- #END NOME EVENTO/DATA/LOCAL/AVALIAÇÃO -->
		
		</div>
		
		<!-- DETAILS EVENT -->	
		
		<div class="ct_desc_event" id="show_<?php echo $evento->id ?>">
			<div class="desc_event">
				
				<span class="title_details">Descrição</span><br>
				<span class="text_desc"><?php echo $evento->descricao ?></span>
				
			</div> 
		</div>
		
		
		<!-- PROMO PAGE EVENT -->
		
		<div class="ct_promo_event" id="showpromo_<?php echo $evento->id ?>">
		
			<?php if(count($evento->cortesias) > 0) :  //verifica se existem cortesias?>
		
			<table class="promo_table" border="0" cellspacing="0" width="610">
					
			  <tr class="promo_title">
			    <td class="promo_topic">Tipo</td>
			    <td class="promo_topic">Disponíveis</td>
			    <td class="promo_topic_r">Valor</td>
			    <td></td>
			  </tr>
			  
			  	<?php foreach ($evento->cortesias as $cortesias) : ?>
			  	
			  <tr>
			    <td class="promo_info"><?php echo $cortesias->nome ?></td>
			    <td class="promo_info">
			    	<span class="max_destak"><?php echo $cortesias->disponivel ?></span> de <span class="min_destak"><?php echo $cortesias->qtd ?></span>
			    </td>
			    <td class="promo_info">
			    	de <span class="min_destak">R$<?php echo $cortesias->valor_original ?></span> por <span class="max_destak">R$<?php echo $cortesias->valor ?></span>
			    </td>
			    <td class="btn_go_promo cortesia_euquero" id="cortesia_<?php echo $cortesias->id ?>">Eu quero</td>
			  </tr>
						
				<?php endforeach; ?>
					
			</table>
	
			<?php endif;?>
		
		</div>
	
	</div> <!-- FINAL EVENT -->

	<h5>id:<?php echo $evento->id ?>  Nome: <?php echo $evento->nome ?></h5>
	
	Link: 
	<a href="	<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?> ">
		<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?>
	</a>
	<p>
	Realização:	<?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?>
	</p>
	<p>
	Descrição: <?php echo $evento->descricao ?>
	</p>
	<p>
	Parceiro:
		<a href="	<?php echo $this->url(array('id' => $evento->parceiro->id, 'nome' => $evento->parceiro->nome), 'parceiro') ?> ">
		<?php echo $evento->parceiro->nome ?>
		</a>
	</p>
	<p>
	Descrição do parceiro: <?php echo $evento->parceiro->descricao ?>
	</p>
	<p>
	Foto do parceiro: <?php echo $evento->parceiro->foto ?>
	</p>
	
	<p>
	<?php  echo $evento->parceiro->local->rua ?>, <?php echo $evento->parceiro->local->numero ?> <?php echo $evento->parceiro->local->complemento ?>
	<?php  echo $evento->parceiro->local->cidade->nome ?>-<?php echo $evento->parceiro->local->cidade->estado->sigla ?>
	</p>
	
	<?php //if(count($evento->cortesias) > 0) :?>
	
		<h2>Cortesias</h2>
		<?php foreach ($evento->cortesias as $cortesias) : ?>
			Ingresso: <?php echo $cortesias->nome ?> (<?php echo $cortesias->descricao ?>)
			Disponível: <?php echo $cortesias->disponivel ?>
			Valor: <?php echo $cortesias->valor ?>
			<hr />
		<?php endforeach; ?>
	
	<?php //endif;?>
	
	
	<hr />
<?php	endforeach;  ?>





<h2>Destaques</h2>
<?php foreach ($this->destaques as $destaques): ?>
	Data: <?php echo date('d/m/Y', strtotime( $destaques->realizacao)) ?>
	Nome: <?php echo $destaques->nome ?>
	Local: <?php echo $destaques->parceiro->nome ?>
	<br>
	<hr>
<?php endforeach;  ?>	
	
</div> <!-- #END CT LEFT -->

<!-- #START DESTAQUES -->

<div class="ct_right">

	<div class="ct_event_destak" style="width: 346px; float: right; background: url('/img/bg_destak.png') repeat-x; border: 1px solid #E5E5E5;">
	
	<span class="event_date_d" style="float: right; padding: 4px 8px; color: #FFF; background: url('/img/bg_date_destak.png') repeat-x; border-right: 5px solid black;"><?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?></span>
	
		<div class="ct_left_d">
			<div class="ct_flyer_d">
				<img alt="<?php echo $evento->nome ?>" src="/img/eventos/<?php echo $evento->capa?> "/>
			</div>
		</div>
	
		<div class="ct_right_d" style="padding: 18px 0 0;">
		
			<div class="ct_event_date_d">
				<span class="event_name_d">Evento: <?php echo $evento->nome ?></span>
			</div>
			
			<div class="ct_event_local_d">
				<span class="event_local_d">
					Local: <a href="	<?php echo $this->url(array('id' => $evento->parceiro->id, 'nome' => $evento->parceiro->nome), 'parceiro') ?> ">
								<?php echo $evento->parceiro->nome ?>
						   </a>
				</span>
	
			</div>
		
		</div>

	</div>

</div>
	
	

	
<!-- #START DIALOG CORTESIAS -->

<div id="dialog_cortesia"></div><!-- Div modal CONVERTER CORTESIA -->





<?php 
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/show_details_event.js'))
		->prependFile($this->baseUrl('/js/eventos.js'))
		->prependFile($this->baseUrl('/js/jquery-ui-1.9.2.custom.min.js'));

	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/eventos.css'))
	->prependStylesheet($this->baseUrl('/css/pepper-grinder/jquery-ui-1.9.2.custom.min.css'));
?>
