<?php 

	$dias = array();
	$dias_semana = array('Dom', 'Seg', 'Ter', 'Quar', 'Qui', 'Sex', 'Sáb');
	$dias_semana_long = array('Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo');
	$mes_long = array('Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
	    'Outubro','Novembro','Dezembro');
	//$dia_base = time();
	
	if(empty($_GET['d'])){
		$dia_base = time(); //+86400*50;  //86400 = 1 dia
	}else{
		$dia_base = $_GET['d'];
	}
			
	for($i = -1; $i < 6; $i++){
		$dias[] = $dia_base + ($i * 86400);
	}

	$week = array();
	$week['prev'] = ($dias[0]-(86400*4));
	$week['next'] = ($dias[6]+(86400*4));
	$defaulDate = $dias_semana_long[date('w', $dia_base)].", ".date('d', $dia_base) ." de ". $mes_long[(date('n', $dia_base)-1)]. ", ".date('Y', $dia_base);
?>	
	
<script type="text/javascript">
	var defaultDate = "<?php echo $defaulDate; ?>";
</script>

<div id="top_date_search">
	<div style="float: left; width: 420px; max-width: 420px;">
		Exibindo eventos de: <span style="font-weight: bold;"><?php echo $defaulDate; ?></span>
	
	</div>
	<div style="float: left;margin-top: -6px;">
		<a href=""><div id="search"><img src="/img/btn_search.png" /></div></a>
	</div>
</div>
	
<div class="container_calendario" style="border: 1px solid #CCC; width: 620px; display: table;">	
		<ul id="ul_calendar" style="padding: 12px 8px 2px 8px;">
				<?php
					foreach($dias as $dia){
						(date('d/m', $dia) == date('d/m', $dia_base)) ? $active = 'class="active"' : $active = "";
						
						echo "
							<li $active rel='".$dia."'>
								<a href='/eventos?d=".$dia."'>
									".$dias_semana[date('w', $dia)]." ". date('d/m', $dia)."
								</a>
							</li>"
							;
					}
				?>
		</ul>
</div>	

<h5 style="clear:both;">Exibindo eventos de:</h5>
<form>
    <input type="text" name="d" id="d" style="display: none;" value="<?php echo $dia_base ?>" />
    <input type="text" name="date_filter_view" id="date_filter_view"  readonly="readonly" value="<?php echo $defaulDate; ?>" />
    <input type="submit" value="Pesquisar">
</form>
								    
<!-- 							    

					<div id="search_adv">
					
						<div id="categories">
							<ul>
								<li class="iten_category">Bares e Restaurantes</li>
								<li class="iten_category">Casas noturnas</li>
								<li class="iten_category">Cinemas</li>
								<li class="iten_category">Teatros</li>
							</ul>
						</div>
						
						<div id="filter">
					
							<table>
							  <tr>
							    <td class="txt_input_h">Local:</td>
							    <td><input type="" name="local_filter" size="30"/></td>
							    <td class="txt_input_h">Data:</td>
							    <td>
								    <input type="text" name="date_filter_view" id="date_filter_view" />
								    <input type="text" name="date_filter" id="date_filter" />
							    </td>
							  </tr>
							  <tr>
							    <td class="txt_input_h">Genero:</td>
							    <td>
							    	<select name="genre_filter" id="genre_filter">
        								<option value="Rock">Rock</option>
        								<option value="Sertanejo">Sertanejo</option>
        								<option value="Eletronica">Eletronica</option>
      								</select>
      							</td>
							    <td class="txt_input_h">Cidade:</td>
							    <td><input type="" name="city_filter" /></td>
							  </tr>
							  <tr>
							    <td colspan="4"><a href="#" id="btn_go_filter">Buscar</a></td>
							  </tr>
							</table>
				
						</div>
					
					</div>	
 -->						
		
	<?php 
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/busca_avancada.css'));
	


	$this->headScript()->setSeparator(PHP_EOL)
	->appendFile($this->baseUrl('/js/show_search.js'));
	?>

	