		
					<div id="search_adv">
					
						<div id="categories">
							<ul>
								<li class="iten_category">Bares e Restaurantes</li>
								<li class="iten_category">Casas noturnas</li>
								<li class="iten_category">Cinemas</li>
								<li class="iten_category">Teatros</li>
							</ul>
						</div>
						
						<div id="filter">
					
							<table>
							  <tr>
							    <td class="txt_input_h">Local:</td>
							    <td><input type="" name="local_filter" size="30"/></td>
							    <td class="txt_input_h">Data:</td>
							    <td><input type="" name="date_filter" /></td>
							  </tr>
							  <tr>
							    <td class="txt_input_h">Genero:</td>
							    <td>
							    	<select name="genre_filter" id="genre_filter">
        								<option value="Rock">Rock</option>
        								<option value="Sertanejo">Sertanejo</option>
        								<option value="Eletronica">Eletronica</option>
      								</select>
      							</td>
							    <td class="txt_input_h">Cidade:</td>
							    <td><input type="" name="city_filter" /></td>
							  </tr>
							  <tr>
							    <td colspan="4"><a href="#" id="btn_go_filter">Buscar</a></td>
							  </tr>
							</table>
				
						</div>
					
					</div>	
					
					
		
	<?php 
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/busca_avancada.css'));
	?>