<?php 

	$dias = array();
	$dias_semana = array('Dom', 'Seg', 'Ter', 'Quar', 'Qui', 'Sex', 'Sáb');
	$dias_semana_long = array('Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado');
	$dia_base = time();
			
	for($i = -3; $i < 4; $i++){
		$dias[] = $dia_base + ($i * 86400);
	}

	$week = array();
	$week['prev'] = ($dias[0]-(86400*4));
	$week['next'] = ($dias[6]+(86400*4));
?>	

<div class="container_calendario">	
	<div id="date_left" class="date_arrow" rel="<?php echo $week['prev']; ?>"> << </div>
		<ul id="ul_calendar">
				<?php
					foreach($dias as $dia){
						(date('d/m', $dia) == date('d/m', $dia_base)) ? $active = 'class="active"' : $active = "";
						
						echo "<li $active rel='".$dia."'>".$dias_semana[date('w', $dia)]." ". date('d/m', $dia)."</li>";
					}
				?>
		</ul>
	<div id="date_right"class="date_arrow" rel="<?php echo $week['next']; ?>"> >> </div>
</div>	

<h5 style="clear:both;">Exibindo eventos de:</h5>
    <input type="text" name="date_filter_view" id="date_filter_view" value="<?php echo "Quinta, 10 de Janeiro, 2013";//date('d/m/Y', $dia_base)?>" />
    <input type="text" name="date_filter" id="date_filter" style="display: none;" />
								    
<!-- 							    

					<div id="search_adv">
					
						<div id="categories">
							<ul>
								<li class="iten_category">Bares e Restaurantes</li>
								<li class="iten_category">Casas noturnas</li>
								<li class="iten_category">Cinemas</li>
								<li class="iten_category">Teatros</li>
							</ul>
						</div>
						
						<div id="filter">
					
							<table>
							  <tr>
							    <td class="txt_input_h">Local:</td>
							    <td><input type="" name="local_filter" size="30"/></td>
							    <td class="txt_input_h">Data:</td>
							    <td>
								    <input type="text" name="date_filter_view" id="date_filter_view" />
								    <input type="text" name="date_filter" id="date_filter" />
							    </td>
							  </tr>
							  <tr>
							    <td class="txt_input_h">Genero:</td>
							    <td>
							    	<select name="genre_filter" id="genre_filter">
        								<option value="Rock">Rock</option>
        								<option value="Sertanejo">Sertanejo</option>
        								<option value="Eletronica">Eletronica</option>
      								</select>
      							</td>
							    <td class="txt_input_h">Cidade:</td>
							    <td><input type="" name="city_filter" /></td>
							  </tr>
							  <tr>
							    <td colspan="4"><a href="#" id="btn_go_filter">Buscar</a></td>
							  </tr>
							</table>
				
						</div>
					
					</div>	
 -->						
		
	<?php 
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/busca_avancada.css'));
	


	$this->headScript()->setSeparator(PHP_EOL)
	->appendFile($this->baseUrl('/js/show_search.js'));
	?>
	
<script type="text/javascript">
	var defaultDate = "<?php echo date('Y-m-d', $dia_base)?>";
</script>
	
	
	<style>
.date_arrow, ul#ul_calendar{
	float: left;
}
ul#ul_calendar li{
	float: left;
	white-space: nowrap;
	margin: 2px;
	cursor: pointer;
}
ul#ul_calendar li.active, ul#ul_calendar li:hover{
	background:transparent url(/img/date_day_active.png) center center no-repeat;
	color: #000;
}
</style>