
	<div class="footer">
	
		<div class="footer_icon">
			
		</div>

		<div class="footer_menu">
		
			<ul>
				<li><a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'como-funciona'), 'default', true); ?>">Como funciona</a></li>
				<li><a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'divulgar-evento'), 'default', true); ?>">Divulgue seu evento</a></li>
				<!-- <li><a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'trabalhe-conosco'), 'default', true); ?>">Trabalhe conosco</a></li> -->
				<li><a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'contato'), 'default', true); ?>">Contato</a></li>

				<li class="footer_face"><a target="_blank" href="http://www.facebook.com/pages/EVenter/398051346951115"><img src="/img/facebook.png" /></a></li>
			</ul>
		
		</div>
		<div class="footer_end">
			<div>
				<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'politica-de-privacidade'), 'default', true); ?>">
					Política de privacidade
				</a>
			</div>
			<div>
				<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'termos-de-uso'), 'default', true); ?>">
					Termos de uso
				</a>
			</div>
			<div class="copyright">
				Copyright © eventer 
			</div>
		
		</div>
		
	</div>

	<?php
		$this->headLink()->prependStylesheet($this->baseUrl('/css/footer.css'));
	?>