
	<div class="footer">
	
		<div class="footer_icon">
			
		</div>

		<div class="footer_menu">
		
			<ul>
				<li><a href="/">Como funciona</a></li>
				<li><a href="/">Divulgue seu evento</a></li>
				<li><a href="/">Trabalhe conosco</a></li>
				<li><a href="/">Contato</a></li>

				<li class="footer_face"><a target="_blank" href="http://www.facebook.com/pages/EVenter/398051346951115"><img src="/img/facebook.png" /></a></li>
			</ul>
		
		</div>
		<div class="footer_end">
			<div>
				<a href="/privacidade">
					Política de privacidade
				</a>
			</div>
			<div>
				<a href="/termos">
					Termos de uso
				</a>
			</div>
			<div class="copyright">
				Copyright © eventer 
			</div>
		
		</div>
		
	</div>

	<?php
		$this->headLink()->prependStylesheet($this->baseUrl('/css/footer.css'));
	?>