
<div class="header">
	<div class="header_home">
		<a href="/">
			<img src="/img/header_home.png" />
		</a>
	</div>
		

	<div id="navigation_wrap">
							<?php 
					
					if ( !Zend_Auth::getInstance()->hasIdentity() ){
						//echo $this->navigation()->setTranslator(Zend_Registry::get('Zend_Translate'))->menu()->renderMenu(Zend_Registry::get('default'));
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('default'));
						
						$this->headScript()->prependFile($this->baseUrl('/js/login.js'));  //chama o script que tem o login pelo face
						
						?>
				<div id="div_form_login">
					<div id="top_form"></div>
				    <div id="ct_form">
				    	<div id="form">
				    	<form id="form_login_ajax" name="form_login" enctype="application/x-www-form-urlencoded" action="" method="post">

				    	
				          <table border="0">
				            <tr>
				              <td colspan="2">
				                <span class="span1">Informe sua cidade e email e receba todos os eventos de sua região:</span>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" height="60">
				                <input type="text" name="email" id="email" class="input_login" />
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2">
				                <input type="text" name="email" id="email" class="input_login" />
				              </td>
				            </tr>
				            <tr height="80">
				              <td>
				              	<span class="btn_no_city">não encontrou?</span>
				              </td>
				              <td width="180">
				              	<img src="/img/btn_go_sociais.png" />
				              </td>
				            </tr>
				            <tr height="50">
				              <td colspan="2" style="text-align: center;">
				           	   <span class="span2">ou curta nossa fan page</span>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" >
				              	<img src="/img/btn_go_facebook.png" />
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" >
				              	<span class="msg_error">Erro! Verfique os dados digitados.</span>
				              </td>
				            </tr>   
				          </table>
				    	
				    	
				    	
				    	
				    	
				         <!--   <table border="0">
				            <tr>
				              <td colspan="2">
				                <label for="email" class="text_form_login">Seu email</label>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" height="60">
				                <input type="text" name="e" id="e" class="input_login" />
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2">
				                <label for="senha" class="text_form_login">Senha de acesso</label>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" height="60">
				                <input type="password" name="s" id="s" class="input_login" />
				              </td>
				            </tr>
				            <tr height="80">
				              <td width="180">
				              	<span class="text_senha">Esqueceu sua senha? <a href="#" class="link_senha">Clique aqui</a></span>
				              </td>
				              <td>
				             	 <input type="image" src="/img/login_btn_login.png" alt="Login" id="submitbutton" >
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" >
				              	<span class="msg_error">Erro! Verfique os dados digitados.</span>
				              </td>
				            </tr>    
				            <tr height="120">
				              <td colspan="2" >
				              
										<div id="container_fb-auth" style="display: block;text-align: center; float: left; margin-top: 6px;" >
											<div id="fb-auth-loading" style="display: none; float: left; text-align: center;margin: 3px 0 0 40px;">
												<img src="/img/loading_face.gif" style="text-align: center;" />
											</div>
											<div id="fb-auth-button" style="float: left; cursor: pointer; text-align: center;" >
												<img id="fb-auth" src="/img/login_face.png" style="text-align: center;" />
											</div>
										</div>				              
				              
				              </td>
				            </tr>
				
				          </table> -->
						</form>
				          
				         </div>
				    </div>
				</div>
				
			<?php 
				}else {
					echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('logged'));
					}
						
			?>	
	</div>	
		
</div>

	<?php
	$this->headLink()->prependStylesheet($this->baseUrl('/css/header.css'));
	?>
