
<div class="header">
	<div class="header_home">
		<a href="/">
			<img src="/img/header_home.png" />
		</a>
	</div>
		
	
	<div class="header_social">
		<div class='social hs_fb'>
			<div class="fb-like" data-href="http://www.facebook.com/pages/EVenter/398051346951115" data-layout="button_count" data-send="false" data-width="50" data-show-faces="false"></div>
		</div>
		<div class='social hs_plus'>
			<div class="g-plusone" data-size="medium" data-href="https://plus.google.com/116229421147699373151"></div>
		</div>
		<div class='social hs_tw'>
			<a href="https://twitter.com/eVenter_oficial" class="twitter-follow-button" data-width="50"  data-show-count="true" data-lang="pt" data-show-screen-name="false">Seguir @eVenter_oficial</a>
		</div>
	</div>
<style>
/****** Floating page sharer *******/
.header_social {
	position: absolute; 
	top: 5px; 
	left: 100px;
	padding:5px 3px 3px 5px; 
	float:left; 
	text-align:center;
}
.header_social .social {float:left;}
/* .header_social .social#fb {margin: 0 0 3px 4px;} */
.header_social .hs_plus {margin-left: 15px; width: 60px;}
.header_social .hs_tw {margin-left: 15px;}
/* .header_social .social#tw iframe {width: 53px !important;} */
</style>		

	<div id="navigation_wrap">
							<?php 
					
					if ( !Zend_Auth::getInstance()->hasIdentity() ){
						//echo $this->navigation()->setTranslator(Zend_Registry::get('Zend_Translate'))->menu()->renderMenu(Zend_Registry::get('default'));
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('default'));
						
						$this->headScript()->prependFile($this->baseUrl('/js/login.js'));  //chama o script que tem o login pelo face
						
						?>				
						
				<div id="div_form_login">
					<div id="top_form"></div>
					<?php /*
						<div id="loading_news_form">
						<?php 
							 $form = new Application_Form_News();
							 echo $form;
						?>
						</div>
						
						<button id="submit_news">RECEBER EVENTOS NO EMAIL</button>
						*/ ?>
						<p style="margin:0 10px;">
							<b>Curta</b> nossa fanpage e fique por dentro das novidades!
						</p>
						<div >
							<div class="fb-like" data-href="http://www.facebook.com/pages/EVenter/398051346951115" data-send="true" data-width="358" data-show-faces="true" style=" 
						background: rgb(255,255,255); /* Old browsers */
						/* IE9 SVG, needs conditional override of 'filter' to 'none' */
						background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjQ3JSIgc3RvcC1jb2xvcj0iI2Y2ZjZmNiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNlZGVkZWQiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
						background: -moz-linear-gradient(top,  rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%); /* FF3.6+ */
						background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,1)), color-stop(47%,rgba(246,246,246,1)), color-stop(100%,rgba(237,237,237,1))); /* Chrome,Safari4+ */
						background: -webkit-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* Chrome10+,Safari5.1+ */
						background: -o-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* Opera 11.10+ */
						background: -ms-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* IE10+ */
						background: linear-gradient(to bottom,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* W3C */
						filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ededed',GradientType=0 ); /* IE6-8 */
						padding: 6px 0px 0px 3px; border-radius: 0px 0px 4px 4px; margin: 20px 0 0 0;"></div>						
						</div>
				</div>
						
						
				
				
			<?php 
				}else {
					echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('logged'));
					}
						
			?>	
	</div>	
		
</div>

	<?php
	$this->headLink()->prependStylesheet($this->baseUrl('/css/header.css'));
	?>
