
<div class="header">
	<div class="header_home">
		<a href="/">
			<img src="/img/header_home.png" />
		</a>
	</div>
		

	<div id="navigation_wrap">
							<?php 
					
					if ( !Zend_Auth::getInstance()->hasIdentity() ){
						//echo $this->navigation()->setTranslator(Zend_Registry::get('Zend_Translate'))->menu()->renderMenu(Zend_Registry::get('default'));
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('default'));
						
						$this->headScript()->prependFile($this->baseUrl('/js/login.js'));  //chama o script que tem o login pelo face
						
						?>				
						
				<div id="div_form_login">
					<div id="top_form"></div>
						<div id="loading_news_form">
						<?php 
							 $form = new Application_Form_News();
							 echo $form;
						?>
						</div>
						<button id="submit_news">RECEBER EVENTOS NO EMAIL</button>
						<div >
							<div class="fb-like" data-href="http://www.facebook.com/pages/EVenter/398051346951115" data-send="true" data-width="358" data-show-faces="true" style=" 
						background: rgb(255,255,255); /* Old browsers */
						/* IE9 SVG, needs conditional override of 'filter' to 'none' */
						background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iI2ZmZmZmZiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjQ3JSIgc3RvcC1jb2xvcj0iI2Y2ZjZmNiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiNlZGVkZWQiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
						background: -moz-linear-gradient(top,  rgba(255,255,255,1) 0%, rgba(246,246,246,1) 47%, rgba(237,237,237,1) 100%); /* FF3.6+ */
						background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,255,255,1)), color-stop(47%,rgba(246,246,246,1)), color-stop(100%,rgba(237,237,237,1))); /* Chrome,Safari4+ */
						background: -webkit-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* Chrome10+,Safari5.1+ */
						background: -o-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* Opera 11.10+ */
						background: -ms-linear-gradient(top,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* IE10+ */
						background: linear-gradient(to bottom,  rgba(255,255,255,1) 0%,rgba(246,246,246,1) 47%,rgba(237,237,237,1) 100%); /* W3C */
						filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#ededed',GradientType=0 ); /* IE6-8 */
						padding: 6px 0px 0px 3px; border-radius: 0px 0px 4px 4px; margin: 20px 0 0 0;"></div>						
						</div>
				</div>
						
						<?php /*
				<div id="div_form_login">
					<div id="top_form"></div>
				    <div id="ct_form">
				    	<div id="form">
				    	<form id="form_news_ajax" name="form_login" enctype="application/x-www-form-urlencoded" action="" method="post">

				    	
				          <table border="0">
				            <tr>
				              <td colspan="2">
				                <span class="span1">Informe sua cidade e email e receba todos os eventos de sua região:</span>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" height="60">
								<select name="news_id_cidade" id="news_id_cidade" class="input_login" >
								    <option value="0"></option>
								    <?php 
									    $cidades = new Application_Model_DbTable_LocalCidades();
									    foreach ($cidades->getCidadesList() as $cidade) :
								    ?>
								    <option value="<?php echo $cidade['key'] ?>"><?php echo $cidade['value'] ?></option>
								    <?php endforeach;?>
								</select>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2">
				                <input type="text" name="news_email" id="news_email" class="input_login" />
				              </td>
				            </tr>
				            <tr height="80">
				              <td>
				              	<span class="btn_no_city">não encontrou?</span>
				              </td>
				              <td width="180">
				              	 <input type="image" src="/img/btn_go_sociais.png" alt="Login" id="submitbutton" >
				              </td>
				            </tr>
				            <tr height="50">
				              <td colspan="2" style="text-align: center;">
				           	   <span class="span2">ou curta nossa fan page</span>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" >
				              	<img src="/img/btn_go_facebook.png" />
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" >
				              	<span class="msg_error">Erro! Verfique os dados digitados.</span>
				              </td>
				            </tr>   
				          </table>
				    	
				    	
				    	
				    	
				    	
				         <!--   <table border="0">
				            <tr>
				              <td colspan="2">
				                <label for="email" class="text_form_login">Seu email</label>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" height="60">
				                <input type="text" name="e" id="e" class="input_login" />
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2">
				                <label for="senha" class="text_form_login">Senha de acesso</label>
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" height="60">
				                <input type="password" name="s" id="s" class="input_login" />
				              </td>
				            </tr>
				            <tr height="80">
				              <td width="180">
				              	<span class="text_senha">Esqueceu sua senha? <a href="#" class="link_senha">Clique aqui</a></span>
				              </td>
				              <td>
				             	 <input type="image" src="/img/login_btn_login.png" alt="Login" id="submitbutton" >
				              </td>
				            </tr>
				            <tr>
				              <td colspan="2" >
				              	<span class="msg_error">Erro! Verfique os dados digitados.</span>
				              </td>
				            </tr>    
				            <tr height="120">
				              <td colspan="2" >
				              
										<div id="container_fb-auth" style="display: block;text-align: center; float: left; margin-top: 6px;" >
											<div id="fb-auth-loading" style="display: none; float: left; text-align: center;margin: 3px 0 0 40px;">
												<img src="/img/loading_face.gif" style="text-align: center;" />
											</div>
											<div id="fb-auth-button" style="float: left; cursor: pointer; text-align: center;" >
												<img id="fb-auth" src="/img/login_face.png" style="text-align: center;" />
											</div>
										</div>				              
				              
				              </td>
				            </tr>
				
				          </table> -->
						</form>
				          
				         </div>
				    </div>
				</div>
				*/
				?>
				
			<?php 
				}else {
					echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('logged'));
					}
						
			?>	
	</div>	
		
</div>

	<?php
	$this->headLink()->prependStylesheet($this->baseUrl('/css/header.css'));
	?>
