<?php 
$parceiro = $this->parceiro; 

//print_r($parceiro);
?>

<div class="parceiro_header">
	<div class="parceiro_header_wrap">

		<div class="parceiro_summary">
			<div class="parceiro_logo">
				<img alt="<?php echo $parceiro->nome ?>" src="/img/parceiros/<?php echo $parceiro->foto?> "/>
			</div>
			<div class="parceiro_data">
				<h2><?php echo $parceiro->nome ?></h2>
				<h3><?php echo $parceiro->local->nome ?> - <?php echo $parceiro->local->estado->sigla ?><span>(<?php echo implode(', ', $parceiro->atividades); ?>)</span></h3>
			</div>
			<div class="facebook_like">
				<iframe src="//www.facebook.com/plugins/like.php?href=<?php echo $this->serverUrl() .'/' . $parceiro->url_amigavel ?>&amp;send=false&amp;layout=button_count&amp;width=140&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21&amp;appId=240996152682246" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:140px; height:21px;" allowTransparency="true"></iframe>
			</div>
		</div>
		

		
		<div class="parceiro_information">
		
			<ul>
				<li>
					<div id="rate_<?php echo $parceiro->id; ?>">
   						<ul class="star-rating" style="margin: 0 auto; margin-top: 4px;">
   							<li class="current-rating" id="current-rating" style="width: <?php echo ($parceiro->rating * 20); ?>%;"></li>
						    <li><a href="#" title="Péssimo" rel="<?php echo $parceiro->id ?>" class="star1" >1</a></li>
						    <li><a href="#" title="Ruim" rel="<?php echo $parceiro->id ?>" class="star2" >2</a></li>
						    <li><a href="#" title="Regular" rel="<?php echo $parceiro->id ?>" class="star3" >3</a></li>
						    <li><a href="#" title="Bom" rel="<?php echo $parceiro->id ?>" class="star4" >4</a></li>
						    <li><a href="#" title="Ótimo" rel="<?php echo $parceiro->id ?>" class="star5" >5</a></li>
						</ul>
					</div>
				
				</li>
				<?php /*
				<li class="panel_label">
					<button><span>Horários</span></button>
					<div class="panel_value">
						<?php echo $parceiro->funcionamento ?>
					</div>
				</li>
				<li class="panel_label">
					<button><span>Formas de pgto</span></button>
					<div class="panel_value">
						<?php echo $parceiro->pagamento ?>
					</div>
				</li>
				*/ ?>
			</ul>
		</div>

		</div>
	</div>




	<div class="parceiro_menu">
		<div class="parceiro_menu_wrap">
		<?php 
			$router = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); 
		?>
			<ul>
				<li>
					<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'home'), 'default', true) ?>">
						Home
						<?php if($router == 'home') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
				<?php /*
				<li>
					<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'evento'), 'default', true) ?>">
						Evento
						<?php if($router == 'evento') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
				*/ ?>
				<li>
					<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'agenda'), 'default', true) ?>">
						Agenda
						<?php if($router == 'agenda'|| $router == 'parceiro') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'fotos'), 'default', true) ?>">
						Fotos
						<?php if($router == 'fotos') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'localizacao'), 'default', true) ?>">
						Mapa
						<?php if($router == 'localizacao') echo '<div class="menu_active"></div>'; ?>
					</a>
	  			</li>
			</ul>
		</div>
	</div>



<hr class="parceiro_bar" />

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/parceiro_header.css'));
	$this->headScript()->prependFile($this->baseUrl('/js/parceiro_header.js')); 
?>
						