<?php 
$parceiro = $this->parceiro; 
?>



<div class="parceiro_header">
	<div class="parceiro_header_wrap">

		<div class="parceiro_summary">
			<div class="parceiro_logo">
				<img alt="<?php echo $parceiro->nome ?>" src="/img/parceiros/<?php echo $parceiro->foto?> "/>
			</div>
			<div class="parceiro_data">
				<h2><?php echo $parceiro->nome ?></h2>
				<h3><?php echo $parceiro->local->cidade->nome ?> - <?php echo $parceiro->local->cidade->estado->sigla ?><span>(<?php echo implode(', ', $parceiro->atividades); ?>)</span></h3>
				<h4>Ver descrição do local</h4>
			</div>
		</div>
		
		<div class="parceiro_information">
			<ul>
				<li>
					<div id="rate_<?php echo $parceiro->id; ?>">
   						<ul class="star-rating" style="margin: 0 auto; margin-top: 4px;">
   							<li class="current-rating" id="current-rating" style="width: <?php echo ($parceiro->rating * 20); ?>%;"></li>
						    <li><a href="#" title="Péssimo" rel="<?php echo $parceiro->id ?>" class="star1" >1</a></li>
						    <li><a href="#" title="Ruim" rel="<?php echo $parceiro->id ?>" class="star2" >2</a></li>
						    <li><a href="#" title="Regular" rel="<?php echo $parceiro->id ?>" class="star3" >3</a></li>
						    <li><a href="#" title="Bom" rel="<?php echo $parceiro->id ?>" class="star4" >4</a></li>
						    <li><a href="#" title="Ótimo" rel="<?php echo $parceiro->id ?>" class="star5" >5</a></li>
						</ul>
					</div>
				
				
				</li>
				<li class="panel_label">
					<button><span>Horários</span></button>
					<div class="panel_value">
						<?php echo $parceiro->funcionamento ?>
					</div>
				</li>
				<li class="panel_label">
					<button><span>Formas de pgto</span></button>
					<div class="panel_value">
						<?php echo $parceiro->pagamento ?>
					</div>
				</li>
			</ul>
		</div>

	</div>
</div>




<div class="parceiro_menu">
	<div class="parceiro_menu_wrap">
	<?php 
		$router = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); 
	?>
		<ul>
			<li>
				<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'evento'), 'default', true) ?>">
					Evento
					<?php if($router == 'evento') echo '<div class="menu_active"></div>'; ?>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'agenda'), 'default', true) ?>">
					Agenda
					<?php if($router == 'agenda'|| $router == 'parceiro') echo '<div class="menu_active"></div>'; ?>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'fotos'), 'default', true) ?>">
					Fotos
					<?php if($router == 'fotos') echo '<div class="menu_active"></div>'; ?>
				</a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'localizacao'), 'default', true) ?>">
				Localização
					<?php if($router == 'localizacao') echo '<div class="menu_active"></div>'; ?>
				</a>
			</li>
				<li>
					<a href="<?php echo $this->url(array('controller' => $parceiro->url_amigavel, 'action' => 'contato'), 'default', true) ?>">
					Contato
					<?php if($router == 'contato') echo '<div class="menu_active"></div>'; ?>
				</a>
			</li>
		</ul>
	</div>
</div>



<hr class="parceiro_bar" />



<style>
div.parceiro_header
{
	height: 216px;
	background: transparent url("/img/parceiro_header_back.png");
}
div.parceiro_header div.parceiro_header_wrap 
{
	width: 980px;
	margin: 0 auto;
}
div.parceiro_header div.parceiro_header_wrap div.parceiro_summary
{
	float: left;
	margin-top: 36px;
}

div.parceiro_header div.parceiro_header_wrap div.parceiro_summary div.parceiro_logo {
	background: transparent url("/img/parceiro_logo_mold.png") center center no-repeat;
	width: 142px;
	height: 150px;
	float: left;
}
div.parceiro_header div.parceiro_header_wrap div.parceiro_summary div.parceiro_logo img {
	width: 134px;
	height: 134px;
	margin: 4px;
}
div.parceiro_header div.parceiro_header_wrap div.parceiro_summary  div.parceiro_data
{
	float: left;
	margin: 25px 0 0 20px;
	width: 390px;
}
div.parceiro_header div.parceiro_header_wrap div.parceiro_summary  div.parceiro_data h2
{
	color: #006699;
	font-size: 38px;
	line-height: 105%;
}


div.parceiro_header div.parceiro_header_wrap div.parceiro_summary  div.parceiro_data h3
{
	color: #333333;
	font-size: 15px;
	padding: 8px 6px;
	font-weight: bold;
}

div.parceiro_header div.parceiro_header_wrap div.parceiro_summary  div.parceiro_data h3 span
{
	color: #CCCCCC;
	font-size: 16px;
	padding: 2px 6px;
	font-weight: normal;
}

div.parceiro_header div.parceiro_header_wrap div.parceiro_summary  div.parceiro_data h4
{
	color: #666666;
	font-size: 14px;
	clear: both;
	padding-left: 12px;
	background: transparent url("/img/global_list_icon.png") center left no-repeat;
}


div.parceiro_header div.parceiro_header_wrap div.parceiro_information
{
	float: right;
	margin-top: 70px;
}
div.parceiro_header div.parceiro_header_wrap div.parceiro_information ul li
{
	float: left;
	margin: 0 5px;
}
div.parceiro_header div.parceiro_header_wrap div.parceiro_information ul li button
{
	text-transform: uppercase;
	-webkit-box-shadow: 1px 1px 4px rgba(50,50,50,0.25); 
 	-moz-box-shadow: 1px 1px 3px rgba(50,50,50,0.25); 
 	box-shadow: 1px 1px 3px rgba(50,50,50,0.25); 
}


div.parceiro_menu
{
	height: 73px;
	background-color: #F1F6F9;
}
div.parceiro_menu div.parceiro_menu_wrap
{
	margin: 0 auto;
	width: 850px;
}


div.parceiro_menu div.parceiro_menu_wrap ul li
{
	float: left;
	font-size: 26px;
	margin: 0 1px;
	background-color: #C9E6FB;
	width: 168px;
	text-align: center;
	text-transform: uppercase;
	font-weight: bold;
}
div.parceiro_menu div.parceiro_menu_wrap ul li a:HOVER
{
	color: #00B0DD;
}

div.parceiro_menu div.parceiro_menu_wrap ul li a
{
	line-height: 73px;
	color: #00CCFF;
	display: block;
	position: relative;
}

div.parceiro_menu div.parceiro_menu_wrap ul li div.menu_active {
	background: transparent url("/img/parceiro_menu_active.png") center bottom no-repeat;
	position: absolute;
	left: 65px;
	bottom: -16px;
	width: 32px;
	height: 16px;
}


hr.parceiro_bar
{
	background: transparent url("/img/eventos_calendar_line.png") top center repeat-x;
	height: 10px;
}








/* *****  RATING  ***** */

.star-rating,
.star-rating a:hover,
.star-rating a:active,
.star-rating .current-rating{
background: url(/img/stars_rating.png) left -1000px repeat-x;
cursor: pointer;
}
.star-rating{
position:relative;
width:110px;
height:23px;
overflow:hidden;
list-style:none;
margin:0;
padding:0;
background-position: left top;
}
.star-rating li{
display: inline;
}
.star-rating a,
.star-rating .current-rating{
position:absolute;
top:0;
left:0;
text-indent:-1000em;
height:24px;
line-height:24px;
outline:none;
overflow:hidden;
border: none;
}
.star-rating a:hover,
.star-rating a:active{
background-position: left bottom;
}
.star-rating a.star1{
width:20%;
z-index:6;
}
.star-rating a.star2{
width:40%;
z-index:5;
}
.star-rating a.star3{
width:60%;
z-index:4;
}
.star-rating a.star4{
width:80%;
z-index:3;
}
.star-rating a.star5{
width:100%;
z-index:2;
}
.star-rating .current-rating{
z-index:1;
margin: 0 !important;
background-position: left center;
}	

</style>