		<div id="ct_rodape">
			<div id="rodape">
				<ul style="float: left; padding: 0px 100px 0 0;">
					<li>Projeto.com</li>
					<li style="margin: 4px 12px;">Como funciona</li>
					<li style="margin: 4px 12px;">Postos de retirada</li>
				</ul>

				<ul style="float: left; padding: 0px 100px 0 0;">
					<li>Negócio</li>
					<li style="margin: 4px 12px;">Divulgue seu evento</li>
					<li style="margin: 4px 12px;">Trabalhe conosco</li>
				</ul>

				<ul style="float: left; padding: 0px 100px 0 0;">
					<li>Contato</li>
					<li style="margin: 4px 12px;">Fale conosco</li>
				</ul>
				
				<ul style="float: left; padding: 0px 100px 0 0;">
					<li>SOCIAIS</li>
					<li style="margin: 4px 12px; float: left;">Facebook</li>
					<li style="margin: 4px 12px; float: left;">Twitter</li>
				</ul>
				
			</div>
		</div>
		
	<?php 
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/rodape.css'));
	?>	