		
		<div id="ct_menu" style="text-align: center;"><!-- [start] ct_menu -->
		
			<div id="top_menu"> <!-- [start] top_menu -->
		
				<div class="top_home">
	<!-- 				<a href="?l=pt_BR">[pt]</a> -->
	<!-- 				<a href="?l=en">[en]</a> -->
	
					<a href="/"><div class="ico_home"></div></a>
					
					<div class="sociais_top" style="float: left; padding: 0 20px;">
						<iframe src="http://www.facebook.com/plugins/like.php?href=http://www.seusite.com.br&layout=button_count&show_faces=false&width=80&action=like&font=lucida+grande&colorscheme=light" allowtransparency="true" style="border: medium none; overflow: hidden; width: 80px; height: 21px;" frameborder="0" scrolling="no"></iframe>
					</div>
	
				</div>
				
				<div class="top_menus" id="content_top_menus">
					<?php 
					
					if ( !Zend_Auth::getInstance()->hasIdentity() ){ 
						//echo $this->navigation()->setTranslator(Zend_Registry::get('Zend_Translate'))->menu()->renderMenu(Zend_Registry::get('default'));
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('default'));
						?>
						<div id="div_form_ajax">
							<div class="top_form_ajax"></div>
							<div id="div_msg_error_login"></div>	
							<form id="form_login" name="form_login" enctype="application/x-www-form-urlencoded" action="" method="post">
								<dl class="zend_form">
									<dt id="email-label">
										<label for="email" class="required" style="text-align: left;">Email:</label>
									</dt>
									<dd id="email-element">
										<input type="text" name="email" id="email" value="">
									</dd>
									<dt id="senha-label">
										<label for="senha" class="required" style="text-align: left;">Senha:</label>
									</dt>
									<dd id="senha-element">
										<input type="password" name="senha" id="senha" value="">
									</dd>
									<dd id="submit-element">
										<input type="submit" name="submit" id="submitbutton" value="Logar">
									</dd>
								</dl>
							</form>
						</div>	

						<?php 
					}else {
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('logged'));
						}
						
					?>	

				</div>
				
			</div> <!-- [end] top_menu -->

		</div><!-- [end] ct_menu -->
		
		
		
	<?php
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/topo.css'));

	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/topo.js'))
	?>