		
		<div id="ct_menu" style="text-align: center;"><!-- [start] ct_menu -->
		
			<div id="top_menu"> <!-- [start] top_menu -->
		
				<div class="top_home">
	<!-- 				<a href="?l=pt_BR">[pt]</a> -->
	<!-- 				<a href="?l=en">[en]</a> -->
				<iframe src="http://www.facebook.com/plugins/like.php?href=http://www.seusite.com.br&layout=button_count&show_faces=false&width=80&action=like&font=lucida+grande&colorscheme=light" allowtransparency="true" style="border: medium none; overflow: hidden; width: 80px; height: 21px;" frameborder="0" scrolling="no"></iframe>
				
				</div>
				
				<div class="top_menus">
					<?php 
					
					if ( !Zend_Auth::getInstance()->hasIdentity() ){ 
						//echo $this->navigation()->setTranslator(Zend_Registry::get('Zend_Translate'))->menu()->renderMenu(Zend_Registry::get('default'));
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('default'));
					}else {
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('logged'));
						}
						
					?>	
				</div>
				
			</div> <!-- [end] top_menu -->

		</div><!-- [end] ct_menu -->
		
		
		
	<?php 
	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/topo.css'));
	?>	