<h2>Credenciais</h2>

<form id="form_credenciais" enctype="multipart/form-data" method="post" action="">
	<dt id="parceiro-label">
		<label for="parceiro" class="required">
			Parceiro
		</label>
	</dt>
	<dd id="parceiro-element">
		<select name="parceiro" id="parceiro">
			<option value="0" label="Selecione">Selecione</option>
			<?php foreach ($this->parceiros as $parceiro) :?>
				<option value="<?php echo $parceiro['key']?>" label="<?php echo $parceiro['value']?>"><?php echo $parceiro['value']?></option>
			<?php endforeach;?>
		</select>
	</dd>
	
	<dt id="usuario-label">
		<label for="usuario" class="required">
			Usuario [email] 
		</label>
	</dt>
	<dd id="usuario-element">
		<select name="usuario" id="usuario">
			<option value="0" label="Selecione">Selecione</option>
			<?php foreach ($this->emails as $email) :?>
				<option value="<?php echo $email['key']?>" label="<?php echo $email['value']?>"><?php echo $email['value']?></option>
			<?php endforeach;?>
		</select>
	</dd>
	
	
	
	<dt id="submit-label">
		&#160;
	</dt>
	<dd id="submit-element">
		<input type="submit" name="submit" id="submit" value="Salvar">
	</dd>	
</form>

    
    <div class="progress">
        <div class="bar"></div >
        <div class="percent">0%</div >
    </div>
    
    <div id="status"></div>

 
 
    
    
    
<table id="table_credenciais" summary="Áreas de delivery">
    <thead>
    	<tr>
        	<th scope="col">Parceiro</th>
            <th scope="col">Usuário</th>
            <th scope="col">Del</th>
        </tr>
    </thead>
    <tbody>
	<?php foreach ($this->credenciais as $credencial) :?>
		<tr>
		    <td><?php echo $credencial->parceiro_nome?> (<a target="_blank" href="/<?php echo $credencial->parceiro_url ?>">/<?php echo $credencial->parceiro_url ?></a>)</td>
		    <td><?php echo $credencial->usuario_nome?> (<?php echo $credencial->usuario_email?>) </td>
		    <td><span class="credencial_del" rel="<?php echo $credencial->id?>" style="cursor: pointer;"><img src="/img/bullet_delete.png" /></span></td>
		</tr>
	<?php endforeach;?>
    </tbody>
</table>

    
    
<style>
	.progress { position:relative; width:400px; border: 1px solid #ddd; pad$deliveryding: 1px; border-radius: 3px; }
	.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
	.percent { position:absolute; display:inline-block; top:3px; left:48%; }
	
	
#table_credenciais
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	background: #fff;
	margin: 45px;
/* 	width: 480px; */
	border-collapse: collapse;
	text-align: left;
}
#table_credenciais th
{
	font-size: 14px;
	font-weight: normal;
	color: #039;
	padding: 10px 8px;
	border-bottom: 2px solid #6678b1;
}
#table_credenciais td
{
	border-bottom: 1px solid #ccc;
	color: #669;
	padding: 6px 8px;
	vertical-align: middle;	
}
#table_credenciais tbody tr:hover td
{
	color: #009;
}
	

</style>

    
    
    
<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.form.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/settings/credenciais.js'));
?>