<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br"> 
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
echo 	$this->headTitle(),PHP_EOL;
echo 	$this->headMeta(),PHP_EOL;
?>

<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->


<!--=============================== Mobile Specific Metas  ================================================== -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">



<!--=============================== CSS  ================================================== -->
<link rel="stylesheet" href="/css/base.css"  media="screen" type="text/css" />
<link rel="stylesheet" href="/css/skeleton.css"  media="screen" type="text/css" />
<link rel="stylesheet" href="/css/layout.css"  media="screen" type="text/css" />

<?php 
	echo 	$this->headLink(),PHP_EOL;
?>


</head>
<body>



	<!--=============================== Page Layout ================================================== -->

	
	
	
	
		<!--=============================== Page Navigation TOPO ================================================== -->
		<div id="ct_menu"><!-- [start] ct_menu -->
		
			<div id="top_menu"> <!-- [start] top_menu -->
		
				<div class="top_home">
					<a title="Página Inicial" class="home" href="/">Início</a>
	<!-- 				<a href="?l=pt_BR">[pt]</a> -->
	<!-- 				<a href="?l=en">[en]</a> -->
				</div>
				
				<div class="top_menus">
					<?php 
					
					if ( !Zend_Auth::getInstance()->hasIdentity() ){ 
						//echo $this->navigation()->setTranslator(Zend_Registry::get('Zend_Translate'))->menu()->renderMenu(Zend_Registry::get('default'));
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('default'));
					}else {
						echo $this->navigation()->menu()->renderMenu(Zend_Registry::get('logged'));
						}
						
					?>	
				</div>
				
			</div> <!-- [end] top_menu -->

		</div><!-- [end] ct_menu -->

		<!--=============================== Page TOPO II ================================================== -->
		<div id="ct_top">
			<div id="top">
				<div id="top_left" style="height: 264px; width: 420px; float: left; background: url('/img/bg_top_ii_down.png') center bottom no-repeat;"></div>
				<div id="top_right" style="height: 264px; width: 550px; float: left; background: url('/img/bg_img_top.png') center bottom no-repeat;">
				
					<div style="margin: 224px 0 0 100px; height: 50px; display: table; color: black; font-weight: bold;">
					
						<div style="float: left; margin-right: 4px; padding-right: 20px; background: url('/img/separator.png') no-repeat center right;">
							Você está em:
						</div> 
						
						
						<a href="<?php echo $this->url(array('controller' => 'localidade', 'action' => 'index'), null, true); ?>">
							<div style="color: white; padding-right: 40px; background: url('/img/btn_location.png') no-repeat center right; float: left;">
									<?php echo $this->cityNome ?>
							</div>
						</a>
						
					</div>
				
				</div>
			</div>
		</div>
		
	
	
		<!--=============================== Page Content ================================================== -->	
		<div id="ct_content">
			<div id="content">
			
				<div id="content_left"><!-- [start] content left -->
					<div id="left_top">Exibindo...</div>
				
					<?php echo $this->layout()->content;?>
				</div><!-- [end] content left -->
				
				<div id="content_right"><!-- [start] content right -->
					<div id="right_top">Destaques...</div>
					...
				</div><!-- [end] content right -->
			
			</div>
		</div>

		<!--=============================== Page Rodapé ================================================== -->
		<div id="ct_rodape">
			<div id="rodape">
				<ul class="menu_rodape">
					<li class="title_menu_r">Site.com.br</li>
					<li class="iten_menu_r">Como funciona</li>
					<li class="iten_menu_r">Trabalhe conosco</li>				
				</ul>
				
				<ul class="menu_rodape">
					<li class="title_menu_r">Site.com.br</li>
					<li class="iten_menu_r">Como funciona</li>
					<li class="iten_menu_r">Trabalhe conosco</li>				
				</ul>		
			</div>
		</div>	
<!--=============================== JS ================================================== -->
<?php
/*
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/jquery-1.7.2.min.js'));
		//->prependFile($this->baseUrl('/js/jquery-1.7.2.min.js'));
		 * */
		 
	echo	$this->headScript(),PHP_EOL;
?>

	
	
	
	
<!--=============================== End Document ================================================== -->	
</body>
</html>

