<?php 
	$footer = $this->partial('partials/footer.phtml');
	$header =  $this->partial('partials/header.phtml');

	echo $this->doctype('XHTML1_RDFA');

?>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/" xml:lang="pt-br" lang="pt-br">

<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# eventer_social: http://ogp.me/ns/fb/eventer_social#">

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php 
echo 	$this->headTitle(),PHP_EOL;
echo 	$this->headMeta(),PHP_EOL;
?>



<!--=============================== CSS  ================================================== -->
<link rel="stylesheet" href="/css/base.css"  media="screen" type="text/css" />
<link rel="stylesheet" href="/css/layout.css"  media="screen" type="text/css" />

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/new_style/jquery-ui-1.10.0.custom.css'));
	echo 	$this->headLink(),PHP_EOL;
?>

</head>
<body>


	<!--=============================== Page Layout ================================================== -->
	<div class="global">
		<div class="wrapper">

	
	
	
			<!--=============================== Page Navigation HEADER ================================================== -->
			<?php 
				echo $header;
			?>
	
			<div class="header-extra">
			
				<div class="eventer">
					<a href="/">
						<img alt="eVenter" src="/img/eventer.png" />
					</a>
				</div>
				<?php 
				$atividade = $this->tipo; // $sess->nome;
				?>
				
				<ul class="header-extra_menu">
					<li><a <?php echo ($atividade == 'festa') ? 'class="active"' : ''; ?> href="/eventos/festa/">Festa</a></li>
					<li><a <?php echo ($atividade == 'teatro') ? 'class="active"' : ''; ?>href="/eventos/teatro/">Teatro</a></li>
					<li><a <?php echo ($atividade == 'cinema') ? 'class="active"' : ''; ?>href="/eventos/cinema/">Cinema</a></li>
					<li><a <?php echo ($atividade != 'festas' && $atividade != 'teatro' && $atividade != 'cinema') ? 'class="active"' : ''; ?>href="/eventos/todos/">Todos</a></li>
				</ul>
				
				<div class="img-bg-header"></div>
			
			</div>

		
	
			<!--=============================== Page Content ================================================== -->	
						<?php echo $this->layout()->content;?>
				
		
		
		</div> <!-- <div class="wrapper"> -->
		<!--=============================== Page FOOTER ================================================== -->
		<?php  echo $footer; ?>


	</div> <!-- <div class="global">  -->
	

<!--=============================== JS ================================================== -->
<?php

	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/base.js'))
		->prependFile($this->baseUrl('/js/social_functions.js'))
		->prependFile($this->baseUrl('/js/jquery-ui-1.9.2.custom.min.js'))
		->prependFile($this->baseUrl('/js/jquery-1.7.2.min.js'));	
	
	echo	$this->headScript(),PHP_EOL;
?>

<link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38342261-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	
	
	
<!--=============================== End Document ================================================== -->	
</body>
</html>

