
<?php 
	$footer = $this->partial('partials/footer.phtml');
	$header =  $this->partial('partials/header.phtml');
	$parceiro_header =  $this->partial('partials/parceiro_header.phtml', array('parceiro' => $this->parceiro));	
	echo $this->doctype('XHTML1_RDFA');
?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://opengraphprotocol.org/schema/" xml:lang="pt-br" lang="pt-br">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# eventer_social: http://ogp.me/ns/fb/eventer_social#">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<meta property="fb:page_id" content="398051346951115"/>
<meta property="fb:app_id" content="240996152682246" />
<meta property="og:type" content="eventer_social:event" />
<meta property="og:site_name" content="eVenter - Entradas para o seu evento" />
<meta property="og:image" content="<?php echo $this->serverUrl() ?>/img/logo_eventer.png" />

<?php 
echo 	$this->headTitle(),PHP_EOL;
echo 	$this->headMeta(),PHP_EOL;
?>





<!--=============================== CSS  ================================================== -->
<link rel="stylesheet" href="/css/base.css"  media="screen" type="text/css" />
<link rel="stylesheet" href="/css/parceiro.css"  media="screen" type="text/css" />

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/new_style/jquery-ui-1.10.0.custom.min.css'));
	echo $this->headLink(),PHP_EOL;
?>

</head>
<body>


	<!--=============================== Page Layout ================================================== -->
	<div class="global">
		<div class="wrapper">

	
	
	
			<!--=============================== Page Navigation HEADER ================================================== -->
			<?php 
				echo $header;
			?>
	
	
			<?php 
				echo $parceiro_header;
			?>
	
			<!--=============================== Page Content ================================================== -->	
				<div class="parceiro_content">
					<?php echo $this->layout()->content;?>
				</div>	

				
				
		
		</div> <!-- <div class="wrapper"> -->
		<!--=============================== Page FOOTER ================================================== -->
		<?php  echo $footer; ?>


	</div> <!-- <div class="global">  -->
	

<!--=============================== JS ================================================== -->
<?php

	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/base.js'))
		->prependFile($this->baseUrl('/js/social_functions.js'))
		->prependFile($this->baseUrl('/js/jquery-ui-1.9.2.custom.min.js'))
		->prependFile($this->baseUrl('/js/jquery-1.7.2.min.js'));	
		
		 
	echo	$this->headScript(),PHP_EOL;
?>

<link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38342261-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
	
	
	
<!--=============================== End Document ================================================== -->	
</body>
</html>

