


<?php  
$evento = $this->evento; 

$this->headTitle(' Evento ' . $evento->nome);  //titulo da página
?>

	<h5>id:<?php echo $evento->id ?>  Nome: <?php echo $evento->nome ?></h5>
	
	Link: 
	<a href="	<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?> ">
		<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?>
	</a>
	
	<br />
	Realização:	<?php echo date('d/m/Y', strtotime( $evento->realizacao )) ?>
	
	<br />
	Descrição: <?php echo $evento->descricao ?>
	
	
