<div class="wrap_all_adm">

	<div class="wrap_menu">
	
	   	<ul>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'evento-cadastrar'), 'default', true); ?>">
			    	Evento -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceiro-cadastrar'), 'default', true); ?>">
			    	Parceiro -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceirofotos-cadastrar'), 'default', true); ?>">
			    	FOTOS Parceiro -> Cadastrar
			    </a>
			</li>
			<!-- 
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceiro-deletar'), 'default', true); ?>">
			    	parceiroDeletarAction
			    </a>
			</li>
			 -->
			<!-- 
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'evento-deletar'), 'default', true); ?>">
			    	eventoDeletarAction
			    </a>
			</li>
			 -->
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'endereco-cadastrar'), 'default', true); ?>">
			    	Endereco -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'cidade-cadastrar'), 'default', true); ?>">
			    	Cidade -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'estado-cadastrar'), 'default', true); ?>">
			    	Estado -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'estado-cadastrar'), 'default', true); ?>">
			    	ESTATISTICAS
			    </a>
			</li>
		</ul>
	
	</div>
	<div class="wrap_form">


	<?php echo $this->content?>


	</div>
</div>





					
<?php 					
	$this->headLink()
	->prependStylesheet($this->baseUrl('/css/admin.css'));
?>