<?php $parceiro = $this->parceiro;?>

	<div class="ct_btns_top">	
		<ul>
			<li class="btn_top">Avaliação</li>
			<li class="btn_top panel_command" rel="pagamentos">
				Pagamentos <span>»</span>
					<div class="panel_content" id="panel_content_pagamentos">
						<?php echo $parceiro->pagamento ?>
					</div>
			</li>
			<li class="btn_top panel_command" rel="horarios">
				Horários <span>»</span>
					<div class="panel_content" id="panel_content_horarios">
						<?php echo $parceiro->funcionamento ?>
					</div>
			</li>
		</ul>
	</div>
				
<?php 
	$this->headScript()->setSeparator(PHP_EOL)
	->prependFile($this->baseUrl('/js/panels.js'));
	

	$this->headLink()
	->prependStylesheet($this->baseUrl('/css/panels.css'));
?>