<?php $parceiro = $this->parceiro;?>

	<div class="ct_btns_top">	
		<ul>
			<li class="btn_top panel_command" rel="avaliacao">
				Avaliação
					<div class="panel_content" id="panel_content_avaliacao">
							<div id="rate_<?php echo $parceiro->id; ?>">
	   							<ul class="star-rating" style="margin: 0 auto;">
	   								<li class="current-rating" id="current-rating" style="width: <?php echo ($parceiro->rating * 20); ?>%;"></li>
								    <li><a href="#" title="Péssimo" rel="<?php echo $parceiro->id ?>" class="star1" >1</a></li>
								    <li><a href="#" title="Ruim" rel="<?php echo $parceiro->id ?>" class="star2" >2</a></li>
								    <li><a href="#" title="Regular" rel="<?php echo $parceiro->id ?>" class="star3" >3</a></li>
								    <li><a href="#" title="Bom" rel="<?php echo $parceiro->id ?>" class="star4" >4</a></li>
								    <li><a href="#" title="Ótimo" rel="<?php echo $parceiro->id ?>" class="star5" >5</a></li>
								</ul>
							</div>
						
					</div>
			</li>
			<li class="btn_top panel_command" rel="pagamentos">
				Pagamentos <span>»</span>
					<div class="panel_content" id="panel_content_pagamentos">
						<?php echo $parceiro->pagamento ?>
					</div>
			</li>
			<li class="btn_top panel_command" rel="horarios">
				Horários <span>»</span>
					<div class="panel_content" id="panel_content_horarios">
						<?php echo $parceiro->funcionamento ?>
					</div>
			</li>
		</ul>
	</div>
	
	<style>

.star-rating,
.star-rating a:hover,
.star-rating a:active,
.star-rating .current-rating{
background: url(/img/stars_rating.png) left -1000px repeat-x;
cursor: pointer;
}
.star-rating{
position:relative;
width:120px;
height:25px;
overflow:hidden;
list-style:none;
margin:0;
padding:0;
background-position: left top;
}
.star-rating li{
display: inline;
}
.star-rating a,
.star-rating .current-rating{
position:absolute;
top:0;
left:0;
text-indent:-1000em;
height:24px;
line-height:24px;
outline:none;
overflow:hidden;
border: none;
}
.star-rating a:hover,
.star-rating a:active{
background-position: left bottom;
}
.star-rating a.star1{
width:20%;
z-index:6;
}
.star-rating a.star2{
width:40%;
z-index:5;
}
.star-rating a.star3{
width:60%;
z-index:4;
}
.star-rating a.star4{
width:80%;
z-index:3;
}
.star-rating a.star5{
width:100%;
z-index:2;
}
.star-rating .current-rating{
z-index:1;
background-position: left center;
}	
	</style>
				
<?php 
	$this->headScript()->setSeparator(PHP_EOL)
		->prependFile($this->baseUrl('/js/panels.js'))
		->prependFile($this->baseUrl('/js/btns_top.js'));
	

	$this->headLink()
		->prependStylesheet($this->baseUrl('/css/panels.css'))
		->prependStylesheet($this->baseUrl('/css/btns_top.css'));
?>

