
<?php 

	$dias = array();
	$dias_semana = array('Dom', 'Seg', 'Ter', 'Quar', 'Qui', 'Sex', 'Sáb');
	$dias_semana_long = array('Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo');
	$mes_long = array('Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro',
	    'Outubro','Novembro','Dezembro');
	//$dia_base = time();
	
	if(empty($_GET['d'])){
		$dia_base = time(); //+86400*50;  //86400 = 1 dia
	}else{
		$dia_base = $_GET['d'];
	}
	
// 	echo 'dia base '. $dia_base . ' = ' . date('d/m/Y h:i:s', $dia_base);
// 	echo '<hr>time() '. time(). ' = ' . date('d/m/Y h:i:s', time());;
			
	for($i = 0; $i < 7; $i++){
		$dias[] = $dia_base + ($i * 86400);
	}

	$week = array();
	$week['prev'] = ($dias[0]-(86400*6));
	$week['next'] = ($dias[6]+(86400*6));
	$defaultDate = $dias_semana_long[date('w', $dia_base)].", ".date('d', $dia_base) ." de ". $mes_long[(date('n', $dia_base)-1)]. ", ".date('Y', $dia_base);
?>	
	
<script type="text/javascript">
	var defaultDate = "<?php echo $defaultDate; ?>";
</script>

<div class="calendar">
	<div class="calendar_wrap">
		<div class="calendar_container">
			<span class="calendar_arrow">
				<a href="/eventos?d=<?php echo $week['prev'] ?>">
					<img alt="" src="/img/eventos_calendar_arrow_left.png">
				</a>
			</span>
				<ul>
						<?php
							foreach($dias as $dia){
								(date('d/m', $dia) == date('d/m', $dia_base)) ? $active = 'class="active"' : $active = "";
								
								echo "
									<li $active rel='".$dia."'>
										<a href='/eventos?d=".$dia."'>
											<div class='date_week'>
												".$dias_semana[date('w', $dia)]."
											</div>
											<div class='date_month'>
							 					". date('d/m', $dia)."
					    					</div>
				    				";
									if($active != ""){
										echo '<div class="date_active"></div>';
									}				
									echo"
										</a>
									</li>"
									;
							}
						?>
				</ul>
			<span class="calendar_arrow">
				<a href="/eventos?d=<?php echo $week['next'] ?>">
					<img alt="" src="/img/eventos_calendar_arrow_right.png">
				</a>
			</span>
			<span class="calendar_icon">
				<form id="form_busca_eventos">
				    <input style="display: none;" type="text" name="d" id="d" value="<?php echo $dia_base ?>" />
				    <input disabled="disabled" style="display: none;" type="text" name="date_filter_view" id="date_filter_view"  value="<?php echo $defaultDate; ?>" />
				</form>
			</span>
		</div>
	</div>
</div>

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/calendar_partial.css'));
	$this->headScript()->prependFile($this->baseUrl('/js/calendar_partial.js'))
?>