<?php foreach ($this->eventos as $evento): ?>

<div class="evento_wrap">

	<div class="evento_content">
	
		<div class="evento_flyer">
		
			<?php if(count($evento->cortesias) > 0) :  //verifica se existem cortesias?>
				<div class="evento_promo"><img src="/img/evento_flyer_promo.png" /></div>
			<?php endif; ?>
			
			
			<div class="evento_flyer_mold">
				<div class="evento_flyer_img">
					<img alt="<?php echo $evento->nome ?>" src="/img/eventos/<?php echo $evento->capa?> "/>
				</div>
			</div>
		</div>
		
		<div class="evento_description">
		
			<div class="evento_description_label">
				evento:
			</div>
			<div class="evento_description_content">
				<a href="<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?>">
					<?php echo $evento->nome ?>
					
				</a>
			</div>
		
			<div class="evento_description_label">
				local:
			</div>
			<div class="evento_description_content">
			 	<a href="<?php echo $this->url(array('id' => $evento->parceiro->id, 'nome' => $evento->parceiro->nome), 'parceiro') ?>  ">
					<?php echo $evento->parceiro->nome ?>
					
				</a>
			</div>
			
			<button type="button" class="evento_description_button_details">Detalhes</button>
			<?php if(count($evento->cortesias) > 0) : ?>
				<button type="button" class="evento_description_button_promotions" id="btnbonus_<?php echo $evento->id ?>">Promoções</button>
			<?php endif; ?>
		</div>
		
		<div class="evento_date" onclick="">
			<span>
				<?php echo date('d/m/Y', strtotime( $evento->realizacao)) ?>
				
			</span>
			<a href="<?php echo $this->url(array('id' => $evento->id, 'nome' => $evento->nome), 'evento') ?>">
				<?php echo $evento->nome ?>
				
			</a>
		</div>
	
	</div>



	<?php if(count($evento->cortesias) > 0) :  //verifica se existem cortesias?>
		<div class="evento_promotions" id="showpromo_<?php echo $evento->id ?>">
			<table>
				<thead>
				  <tr>
				    <th>Tipo</th>
				    <th>Disponíveis</th>
				    <th>Valor</th>
				    <th class="th_empty"></th>
				  </tr>
				</thead>
				<tbody>
			  	<?php foreach ($evento->cortesias as $cortesias) : ?>
			  	
				  <tr>
				    <td><?php echo $cortesias->nome ?></td>
				    <td>
				    	<span class="max_destak"><?php echo $cortesias->disponivel ?></span> de <span class="min_destak"><?php echo $cortesias->qtd ?></span>
				    </td>
				    <td>
				    	de <span class="min_destak">R$<?php echo $cortesias->valor_original ?></span> por <span class="max_destak">R$<?php echo $cortesias->valor ?></span>
				    </td>
				    <td>
				    	<div class="cortesia_euquero" id="cortesia_<?php echo $cortesias->id ?>" >
				    		Eu quero
				    	</div>
				    </td>
				  </tr>
				<?php endforeach; ?>
				
				</tbody>
			</table>
		</div>
	<?php endif;?>

</div>
<?php endforeach;  ?>



<!-- #START DIALOG CORTESIAS -->

<div id="dialog_cortesia"></div><!-- Div modal CONVERTER CORTESIA -->


	<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/events_partial.css'));
	$this->headScript()->prependFile($this->baseUrl('/js/events_partial.js'))
	?>	
