<?php 
	$sess = new Zend_Session_Namespace('City');
?>

		<div class="location">
			<div class="location_wrap">
				<div class="location_label">
					Cidade:
				</div>
				<div class="location_content">
					<a href="/localidade">
						<?php if($sess->id) :?>
							<?php echo $sess->nome; ?>
						<?php else :?>
							Ainda não selecionada
						<?php endif; ?>
					</a>
				</div>
			</div>
		
		</div>
		
<?php 
if(!$this->clean) {
?>		
<?php 
$cidadesTable = new Application_Model_DbTable_LocalCidades();
$localidades = $cidadesTable->cidadesName();
?>
<div class="ajax_content_localidade">
	<div class="box_text_cities"><span>SELECIONE A CIDADE</span></div>
	<div class="cities">
		<ul>
			<?php foreach ($localidades as $localidade) : ?>
			
				<li>
					<a href="<?php echo $this->url(array('id' => $localidade->id, 'nome' => $localidade->nome), 'localidade') ?> ">
						<?php echo $localidade->nome ?>
						
					</a>
				</li>
			<?php endforeach; ?>
			
		</ul>
	</div>

	<div class="headline">
		Encontre os <span>próximos</span> eventos
	</div>

</div>
<?php 
	$this->headScript()->prependFile($this->baseUrl('/js/location_partial.js'))
?>
<?php  } ?>
		
<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/location_partial.css'));
?>

