<?php 
	$sess = new Zend_Session_Namespace('City');
?>

		<div class="location">
			<div class="location_wrap">
				<div class="location_label">
					Cidade:
				</div>
				<div class="location_content">
					<a href="/localidade">
						<?php if($sess->id) :?>
							<?php echo $sess->nome; ?>
						<?php else :?>
							Ainda não selecionada
						<?php endif; ?>
					</a>
				</div>
			</div>
		
		</div>
		
<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/location_partial.css'));
	$this->headScript()->prependFile($this->baseUrl('/js/location_partial.js'))
?>
