<div class="parceiro_header">


</div>

<div class="parceiro_menu">

</div>

<hr class="parceiro_bar" />

<style>
div.parceiro_header
{
	height: 216px;
	background: transparent url("/img/parceiro_header_back.png");
	border-bottom: 1px dashed #666666
}


div.parceiro_menu
{
	height: 73px;
	background-color: #F1F6F9;
}

hr.parceiro_bar
{
	background: transparent url("/img/eventos_calendar_line.png") top center repeat-x;
	height: 10px;
}
</style>