
	<div class="site_menu">
		<div class="site_menu_wrap">
		<?php 
			$router = Zend_Controller_Front::getInstance()->getRequest()->getActionName(); 
		?>
			<ul>
				<li>
					<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'como-funciona'), 'default', true); ?>">
						Como Funciona
						<?php if($router == 'como-funciona') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'divulgar-evento'), 'default', true); ?>">
						Divulgar
						<?php if($router == 'divulgar-evento') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
				<li>
					<a href="<?php echo $this->url(array('controller' => 'site', 'action' => 'contato'), 'default', true); ?>">
						Contato
						<?php if($router == 'contato'|| $router == 'parceiro') echo '<div class="menu_active"></div>'; ?>
					</a>
				</li>
			</ul>
		</div>
	</div>

<hr class="menu_bar" />

<?php 
	$this->headLink()->prependStylesheet($this->baseUrl('/css/site_header.css'));
?>