<?php 
$cortesia = $this->cortesia;
$usuario = $this->usuario;
?>

	<?php if(!$usuario) : //verifica se existe o usuario ?>
		<h3>Usuário não cadastrado</h3>
		Faça login ou cadastre-se.
		
		
		
	<?php elseif ($usuario->cpf == 0) :  //verifica se o CPF do usuario esta cadastrado ?>
		<h3>CPF inválido</h3>
		Seu CPF é necessário para resgatar o produto, acesse sua conta para cadastra-lo.
			
			
				
	<?php elseif ($cortesia->disponivel < 1) :  //verifica se o CPF do usuario esta cadastrado ?>
		<h3>Esgotado</h3>
		Este produto esgotou. Tente outro produto.
		
		
		
	<?php elseif (($cortesia->evento->ativo) == '0') : //verificar se o evento esta ativo?>
		<h3>Evento não esta ativo</h3>
		O evento ao qual este produto se refere não esta mais ativo. Tente outro evento.
		
		
		
	<?php elseif (($cortesia->termino) <= date('Y-m-d h:i:s') ) : // verifica se ainda esta dentro do prazo para adquirir a cortesia ?>
		<h3>Prazo para troca expirado</h3>
		A data para adquirir este produto já expirou. Tente outro produto.
		
		
		
	<?php elseif (($cortesia->evento->realizacao) < date('Y-m-d')) :  // verifica se o evento já passou ?>
		<h3>Evento já foi realizado</h3>
		A data de realização deste evento foi <?php echo $cortesia->evento->realizacao ?>.
		
		
		
	<?php elseif ($cortesia->sexo != $usuario->sexo  &&  $cortesia->sexo != '3') : //verifica se a cortesia é permitida para o sexo do usuario ?>
		<h3>Produto não disponível para o seu sexo</h3>
		Escolha outro produto ou corrija seu sexo editando os dados de sua conta.

		
		
		
		
	<?php else :  // tudo validado, agora finalmente efetua a troca ?>
	<?php 
	$conversaoTable = new Application_Model_DbTable_Conversao();
	$conversaoTable->converter($cortesia, $usuario);   // converte, grava a converção
	?>
	
	<h3>Adquirido com sucesso</h3>
	Dirija-se até um posto de troca para resgatar seu produto:
	<div><?php echo $cortesia->nome ?></div>
	
		<script type="text/javascript">
		$('#dialog_cortesia').dialog({
			buttons: { "Fechar": function() {
						$(this).dialog("close");
					}
			}
		});
		</script>
 
 	<?php endif; ?>
 
