<?php 
$cortesia = $this->cortesia;
?>



<?php  if($this->logged) :   //==============================se já estiver logado=================//  ?>
	<?php $usuario = $this->usuario; ?>
	
	
	<?php if($cortesia->sexo == '3' || $cortesia->sexo == $usuario->sexo) :  //====== verifica o sexo permitido para a cortesia ?>
			
			<span>(CONFIRMAÇÃO) Item selecionado:</span>
			<ul>
				<li style="background: #EBEBEB; float: left; width: 90px; text-align: right; font-size: 11px; margin: 0 4px 0 0;">Produto: </li>
				<li style="background: #F5F5F5; width: 100%;"><?php echo $cortesia->nome ?></li>
				<li style="margin: 2px;"></li>
				<li style="background: #EBEBEB; float: left; width: 90px; text-align: right; font-size: 11px; margin: 0 4px 0 0;">Descrição: </li>
				<li style="background: #F5F5F5; width: 100%;"><?php echo $cortesia->descricao ?></li>
				<li style="margin: 2px;"></li>
				<li style="background: #EBEBEB; float: left; width: 90px; text-align: right; font-size: 11px; margin: 0 4px 0 0;">Valor: </li>
				<li style="background: #F5F5F5; width: 100%;"> R$<?php echo $cortesia->valor ?></li>
				<li style="margin: 2px;"></li>
				<li style="background: #EBEBEB; float: left; width: 90px; text-align: right; font-size: 11px; margin: 0 4px 0 0;">Disponível: </li>
				<li style="background: #F5F5F5; width: 100%;"><?php echo $cortesia->disponivel ?>/<?php echo $cortesia->qtd ?></li>
				<li style="margin: 2px;"></li>
				<li style="background: #EBEBEB; float: left; width: 90px; text-align: right; font-size: 11px; margin: 0 4px 0 0;">Convertidos: </li>
				<li style="background: #F5F5F5; width: 100%;"><?php echo $qtd_convertidos = count($this->conversoes)?></li>
			</ul>
			
			
			<div id="list_convertidos_<?php echo $cortesia->id ?>">
				<ul>
					<?php foreach ($this->conversoes as $conversoes) :   //============= lista as conversoes ja realizadas para este produto ===========//  ?>
						<li>
							<?php echo date('d/m/Y H:i:s', strtotime( $conversoes->hora )) ?> 
							- 
							<?php echo ( $conversoes->visivel == '1' ) ? $conversoes->usuario->nome : "--Oculto--" ; ?>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
			
			
			
			<script type="text/javascript">


				$('#dialog_cortesia').dialog({
					width: 'auto',
					resizable: true,
					buttons: { "Eu quero !": function(){
								conversao('<?php echo $cortesia->id ?>');
								$('#dialog_cortesia').dialog({
									buttons:{"Cancelar": function(){
											$(this).dialog("close");
										}
									}
								});
							},"Cancelar": function() {
								$(this).dialog("close");
							}
					}
				});
		
				function conversao(id_cortesia){
					$.ajax({
						url: "/conversao/converter", 
						type: "POST", 
						contentType: "application/x-www-form-urlencoded; charset=UTF-8", 
						data: {id_cortesia: id_cortesia},
						success: function (r) {
							$("#dialog_cortesia").html(r);
						}
					});
				}
			</script>	
					
	
	
	
	
	
	<?php else : //================ sexo não é permitido ou usuário não informou o sexo========// ?>
	
		<?php if($usuario->sexo == '0') :?>
			Você ainda não informou seu sexo.
			<hr>
			Vá até sua conta para informar os dados necessários.
			
				<script type="text/javascript">

					$('#dialog_cortesia').dialog({
						buttons: { "Minha Conta": function(){
								location.href= '/usuario';
							},"Cancelar": function() {
								$(this).dialog("close");
							}
						}
					});
				</script>
			
			
			
		<?php else : ?>
			Este tipo de produto não é permitido para o seu sexo
				<script type="text/javascript">

					$('#dialog_cortesia').dialog({
						buttons: {"Cancelar": function() {
								$(this).dialog("close");
							}
						}
					});
				</script>
				
		<?php endif; ?>
	
	
	
	<?php endif;  //================ final da verificação do sexo=========// ?>






	
<?php else :   //===========================se não estiver logado=====================// ?>
		
		<div id="div_msg_error_login" style="font-size: 11px; color: red;"></div>
		
		<div style="border: 1px dotted #CCC; padding: 8px 20px 0px 20px; background: #fbfbfb;">
		
			<?php
				$form = $this->form;
				$form->removeElement('submit');
				echo $form;   //=================mostra o form de login=============//
			?>
		</div>

		<script type="text/javascript">

		$('#dialog_cortesia').dialog({
			buttons: { "Entrar": function(){
					ValidateAjax.doValidate();
				},"Cancelar": function() {
					$(this).dialog("close");
				}
			}
		});

				
			ValidateAjax = {
			    doValidate: function(){
			        $.post('/usuario/validateform',$('#form_login').serialize(),function(response){
			            
			            if(response.status == "sucesso"){
			            	$('#div_msg_error_login').html("Logado");
			            	$("#content_top_menus").html(response.navigation);
			            	converter(<?php echo $cortesia->id ?>);
			            	
			            }else{
			            	$('#div_msg_error_login').html("Falha no login! Preencha corretamente.");
			            }
			        },'json');
			    }
			};
		
		    $('document').ready(function(){
		        $('#form_login').submit(function() {
		        	$('#div_msg_error_login').html("Processando...");
		        	ValidateAjax.doValidate();
		            return false;
		        });
		    });
		
		</script>
 
<?php endif; ?>