

<form id="form_atividades" enctype="multipart/form-data" method="post" action="">

	<dt id="atividades-label">
		<label for="atividades" class="required">
			Tipo/Categoria/Gênero
		</label>
	</dt>
	<dd id="atividades-element">
	<?php foreach ($this->atividades as $atividade) :?>
		<label for="atividades-<?php echo $atividade->id?>">
			<input type="checkbox" name="atividades[]" id="atividades-<?php echo $atividade->id?>" value="<?php echo $atividade->id?>"><?php echo $atividade->nome?>
		</label>
		<br />	
	<?php endforeach;?>
	</dd>

	<dt id="submit-label">
		&#160;
	</dt>
	<dd id="submit-element">
		<input type="submit" name="submit" id="submit" value="Salvar">
	</dd>
	
</form>
    
    
    <div class="progress">
        <div class="bar"></div >
        <div class="percent">0%</div >
    </div>
    
    <div id="status"></div>

 



<table id="table_atividades" summary="Tipos de atividades">
    <thead>
    	<tr>
        	<th scope="col">Tipo</th>
            <th scope="col">Del</th>
        </tr>
    </thead>
    <tbody>
	<?php foreach ($this->atividadesativas as $atividadeativas) :?>
		<tr>
			<td><?php echo $atividadeativas->atividade_nome?></td>
		    <td><span class="atividade_del" rel="<?php echo $atividadeativas->id?>" style="cursor: pointer;"><img src="/img/bullet_delete.png" /></span></td>
		</tr>
	<?php endforeach;?>
    </tbody>
</table>







<style>
	.progress { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
	.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
	.percent { position:absolute; display:inline-block; top:3px; left:48%; }
	
	dd#atividades-element label
	{
		margin: 2px 5px;
		cursor: pointer;
	}
	
#table_atividades
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	background: #fff;
	margin: 45px;
	width: 480px;
	border-collapse: collapse;
	text-align: left;
}
#table_atividades th
{
	font-size: 14px;
	font-weight: normal;
	color: #039;
	padding: 10px 8px;
	border-bottom: 2px solid #6678b1;
}
#table_atividades td
{
	border-bottom: 1px solid #ccc;
	color: #669;
	padding: 6px 8px;
}
#table_atividades tbody tr:hover td
{
	color: #009;
}

</style>


    
<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.form.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/admin/atividades.js'));
?>