<?php if($this->msg) :?>
	<h1><?php echo $this->msg['msg']?></h1>
	
<?php endif;?>
<div class="head_parceirocad">
<a target="_blank" class="linkx" href="/<?php echo $this->parceiro->getUrl_amigavel(); ?>">www.eventer.com.br/<?php echo $this->parceiro->getUrl_amigavel(); ?></a>
</div>
<?php 
	echo $this->form 
?>
	


<?php
	//$this->headScript()->appendFile($this->baseUrl('/js/admin/dados.js'));
?>

<style>
	.head_parceirocad{ padding: 20px 0; text-align: right; font-weight: bold; color: #FFF;}
	.linkx { font-size: 18px; margin-right: 40px;}
</style>