<?php 
	//echo $this->form;
?>

						
<div class="wrap_formall">

<h1>Área Administrativa[<a href="/admin">admin</a>]</h1>

	<div class="wrap_form">
	
		<form id="form_login" name="form_login" enctype="application/x-www-form-urlencoded" action="/usuario/entrar" method="post">
			<dl class="zend_form">
				
				<dt id="email-label">
					<label for="email" class="required">Email:</label>
				</dt>
				
				<dd id="email-element">
					<input type="text" name="email" id="email" value="">
				</dd>
			
				<dt id="senha-label">
					<label for="senha" class="required">Senha:</label>
				</dt>
			
				<dd id="senha-element">
					<input type="password" name="senha" id="senha" value="">
				</dd>
				
				<dt id="submit-label">&#160;</dt>
				<dd id="submit-element">
					<input type="submit" name="submit" id="submitbutton" value="Logar">
				</dd>
			</dl>
		</form>
	
	</div>

</div>

<?php 					
	$this->headLink()
	->prependStylesheet($this->baseUrl('/css/admin.css'));
?>