<?php $form = $this->form ?>

<form id="form_fotos_parceiro" enctype="multipart/form-data" method="post" action="">
	<dl class="zend_form">
		<dt id="url-label">
			<label for="url" class="optional">
				Fotos do parceiro:
			</label>
		</dt>
		<dd>
			<input type="file" name="url[]" id="url" multiple="1">
		</dd>
		<dt id="submit-label">
			&#160;
		</dt>
		<dd id="submit-element">
			<input type="submit" name="submit" id="submit" value="Salvar">
		</dd>
	</dl>
</form>



    
    <div class="progress">
        <div class="bar"></div >
        <div class="percent">0%</div >
    </div>
    
    <div id="status"></div>

    
    
<table id="table_fotos" summary="Fotos do parceiro">
    <thead>
    	<tr>
        	<th scope="col">Fotos</th>
            <th scope="col">Deletar</th>
        </tr>
    </thead>
    <tbody>
	<?php foreach ($this->fotos as $foto) :?>
		<tr>
			<td><a target="_blank" href="/img/parceiros/<?php echo $foto->url?>"> <img src="/img/parceiros/150px/<?php echo $foto->url?>"/> </a></td>
		    <td><span class="foto_del" rel="<?php echo $foto->id?>" style="cursor: pointer;"><img src="/img/bullet_delete.png" /></span></td>
		</tr>
	<?php endforeach;?>
    </tbody>
</table>

    
    
    
<style>
.progress { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
.percent { position:absolute; display:inline-block; top:3px; left:48%; }

	
#table_fotos
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	background: #999;
	width: 960px;
	border-collapse: collapse;
	text-align: left;
}
#table_fotos th
{
	font-size: 14px;
	font-weight: normal;
	color: #000;
	padding: 10px 8px;
	border-bottom: 2px solid #CCC;
}
#table_fotos td
{
	border-bottom: 1px solid #666;
	color: #000;
	padding: 10px 8px 4px 8px;
}
#table_fotos tbody tr:hover td
{
	color: #009;
}

</style>


<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.form.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/admin/fotos.js'));
?>