	

<form id="form_imagem_estab" enctype="multipart/form-data" method="post" action="">
	<dl class="zend_form">
		<dt id="url-label">
			<label for="url" class="optional">
				Imagem do estabelecimento:
			</label>
		</dt>
		<dd>
			<input type="file" name="imagem" id="imagem" >
		</dd>
		<dt id="submit-label">
			&#160;
		</dt>
		<dd id="submit-element">
			<input type="submit" name="submit" id="submit" value="Enviar">
		</dd>
	</dl>
</form>



    
    <div class="progress">
        <div class="bar"></div >
        <div class="percent">0%</div >
    </div>
    
    <div id="status">
    <?php if($this->estab->imagem):?>
    	<img src="/img/estab/<?php echo $this->estab->imagem?>" />
    <?php endif;?>
    </div>
    
    
<style>
.progress { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
.percent { position:absolute; display:inline-block; top:3px; left:48%; }
</style>
    

<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.form.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/admin/imagem.js'));
?>
	
	