
    
    

    
    	<ul>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceiro-cadastrar'), 'default', true); ?>">
			    	parceiroCadastrarAction
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceiro-deletar'), 'default', true); ?>">
			    	parceiroDeletarAction
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'evento-cadastrar'), 'default', true); ?>">
			    	eventoCadastrarAction
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'evento-deletar'), 'default', true); ?>">
			    	eventoDeletarAction
			    </a>
			</li>
		</ul>
			