
    
    

    
    	<ul>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'evento-cadastrar'), 'default', true); ?>">
			    	Evento -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceiro-cadastrar'), 'default', true); ?>">
			    	Parceiro -> Cadastrar
			    </a>
			</li>
			<!-- 
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'parceiro-deletar'), 'default', true); ?>">
			    	parceiroDeletarAction
			    </a>
			</li>
			 -->
			<!-- 
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'evento-deletar'), 'default', true); ?>">
			    	eventoDeletarAction
			    </a>
			</li>
			 -->
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'endereco-cadastrar'), 'default', true); ?>">
			    	Endereco -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'cidade-cadastrar'), 'default', true); ?>">
			    	Cidade -> Cadastrar
			    </a>
			</li>
			<li>
				<a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'estado-cadastrar'), 'default', true); ?>">
			    	Estado -> Cadastrar
			    </a>
			</li>
		</ul>
			