<?php echo $this->partial('partials/admin_partial.phtml'); ?>

<?php $form = $this->form ?>

<form id="form_fotos_parceiro" enctype="multipart/form-data" method="post" action="">
	<dl class="zend_form">
		<dt id="id_parceiro-label">
			<label for="id_parceiro" class="optional">
				Parceiro:
			</label>
		</dt>
		<dd id="id_parceiro-element">
			<?php echo $form->getElement('id_parceiro')?>
		</dd>
		<dt id="url-label">
			<label for="url" class="optional">
				Fotos do parceiro:
			</label>
		</dt>
		<dd>
			<input type="hidden" name="MAX_FILE_SIZE" value="2097152" id="MAX_FILE_SIZE">
			<input type="file" name="url[]" id="url" multiple="1">
		</dd>
		<dt id="submit-label">
			&#160;
		</dt>
		<dd id="submit-element">
			<?php echo $form->getElement('submit')?>
			<dt id="csrf-label">
				&#160;
			</dt>
		<dd id="csrf-element">
			<?php echo $form->getElement('csrf')?>
		</dd>
	</dl>
</form>



    
    <div class="progress">
        <div class="bar"></div >
        <div class="percent">0%</div >
    </div>
    
    <div id="status"></div>
    
    
<style>
.progress { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
.percent { position:absolute; display:inline-block; top:3px; left:48%; }
</style>
    
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<script>
(function() {
    
var bar = $('.bar');
var percent = $('.percent');
var status = $('#status');
   
$('#form_fotos_parceiro').ajaxForm({
    beforeSend: function() {
        status.empty();
        var percentVal = '0%';
        bar.width(percentVal)
        percent.html(percentVal);
    },
    uploadProgress: function(event, position, total, percentComplete) {
        var percentVal = percentComplete + '%';
        bar.width(percentVal)
        percent.html(percentVal);
    },
	complete: function(xhr) {
		status.html(xhr.responseText);
	}
}); 

})();       
</script>