<?php 
	$tipos = $this->tipos;
?>


<form id="form_tipos" enctype="multipart/form-data" method="post" action="">

	<dt id="tipo-label">
		<label for="semana" class="required">
			Tipo/Categoria/Cozinha
		</label>
	</dt>
	<dd id="tipo-element">
	<?php foreach ($tipos as $tipo) :?>
		<label for="tipo-<?php echo $tipo->id?>">
			<input type="checkbox" name="tipo[]" id="tipo-<?php echo $tipo->id?>" value="<?php echo $tipo->id?>"><?php echo $tipo->nome?>
		</label>
		<br />	
	<?php endforeach;?>
	</dd>

	<dt id="submit-label">
		&#160;
	</dt>
	<dd id="submit-element">
		<input type="submit" name="submit" id="submit" value="Salvar">
	</dd>
	
</form>
    
    
    <div class="progress">
        <div class="bar"></div >
        <div class="percent">0%</div >
    </div>
    
    <div id="status"></div>

 



<table id="table_tipos" summary="Tipos de cozinha">
    <thead>
    	<tr>
        	<th scope="col">Tipo</th>
            <th scope="col">Del</th>
        </tr>
    </thead>
    <tbody>
	<?php foreach ($this->tiposativos as $tipoativo) :?>
		<tr>
			<td><?php echo $tipoativo->cozinha_nome?></td>
		    <td><span class="tipo_del" rel="<?php echo $tipoativo->id?>" style="cursor: pointer;"><img src="/img/bullet_delete.png" /></span></td>
		</tr>
	<?php endforeach;?>
    </tbody>
</table>

<pre>
<?php 
	$tipos = $this->tiposativos;
?>

</pre>






<style>
	.progress { position:relative; width:400px; border: 1px solid #ddd; padding: 1px; border-radius: 3px; }
	.bar { background-color: #B4F5B4; width:0%; height:20px; border-radius: 3px; }
	.percent { position:absolute; display:inline-block; top:3px; left:48%; }
	
	dd#semana-element label
	{
		margin: 2px 5px;
		cursor: pointer;
	}
	
#table_tipos
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	background: #fff;
	margin: 45px;
	width: 480px;
	border-collapse: collapse;
	text-align: left;
}
#table_tipos th
{
	font-size: 14px;
	font-weight: normal;
	color: #039;
	padding: 10px 8px;
	border-bottom: 2px solid #6678b1;
}
#table_tipos td
{
	border-bottom: 1px solid #ccc;
	color: #669;
	padding: 6px 8px;
}
#table_tipos tbody tr:hover td
{
	color: #009;
}

</style>


    
<?php 
	$this->headScript()->appendFile($this->baseUrl('/js/jquery.form.js'));
	$this->headScript()->appendFile($this->baseUrl('/js/admin/tipos.js'));
?>