<?php echo $this->partial('partials/location.phtml', array('clean' => true)); ?>

<div class="content_localidade">
	<div class="box_text_cities"><span>SELECIONE A CIDADE</span></div>
	<div class="cities">
		<ul>
			<?php foreach ($this->localidades as $localidade) : ?>
			
				<li>
					<a href="<?php echo $this->url(array('id' => $localidade->id, 'nome' => $localidade->nome), 'localidade') ?> ">
						<?php echo $localidade->nome ?>
						
					</a>
				</li>
			<?php endforeach; ?>
			
		</ul>
	</div>

	<div class="headline">
		Encontre os <span>próximos</span> eventos
	</div>

</div>
	<?php
	$this->headLink()->prependStylesheet($this->baseUrl('/css/localidade.css'));
	?>
	<?php 
	//$this->headScript()->appendFile($this->baseUrl('/js/localidade.js'))
	?>	
	

	<style>
.global
{   
	background: transparent url("/img/body.png") repeat !important;
}
div.content_localidade
{
/* 	background: transparent url("/img/index_back.png") center repeat-x; */
/* 	height: 260px; */
	border-top: 3px solid black;
	background: #4f85bb; /* Old browsers */
	background: #3ba1ef; /* Old browsers */
	/* IE9 SVG, needs conditional override of 'filter' to 'none' */
	background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzNiYTFlZiIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMxNjY3OWUiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
	background: -moz-linear-gradient(top,  #3ba1ef 0%, #16679e 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#3ba1ef), color-stop(100%,#16679e)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top,  #3ba1ef 0%,#16679e 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top,  #3ba1ef 0%,#16679e 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(top,  #3ba1ef 0%,#16679e 100%); /* IE10+ */
	background: linear-gradient(to bottom,  #3ba1ef 0%,#16679e 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3ba1ef', endColorstr='#16679e',GradientType=0 ); /* IE6-8 */
}

div.content_localidade div.cities
{
	float: left;
	margin: 60px 0 0 100px;
	color: #FF9900;
	font-size: 20px;
	line-height: 150%;
}

div.content_localidade div.box_text_cities
{
	border: 1px solid #000; border-top: 0px; position: absolute; left: 100px; padding: 10px 30px; font-size: 16px; color: #CCCCCC;
	background: rgb(0,0,0); /* Old browsers */
	/* IE9 SVG, needs conditional override of 'filter' to 'none' */
	background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIwJSIgeTI9IjEwMCUiPgogICAgPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzAwMDAwMCIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgICA8c3RvcCBvZmZzZXQ9IjEwMCUiIHN0b3AtY29sb3I9IiMzMzMzMzMiIHN0b3Atb3BhY2l0eT0iMSIvPgogIDwvbGluZWFyR3JhZGllbnQ+CiAgPHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz4KPC9zdmc+);
	background: -moz-linear-gradient(top,  rgba(0,0,0,1) 0%, rgba(51,51,51,1) 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(0,0,0,1)), color-stop(100%,rgba(51,51,51,1))); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top,  rgba(0,0,0,1) 0%,rgba(51,51,51,1) 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top,  rgba(0,0,0,1) 0%,rgba(51,51,51,1) 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(top,  rgba(0,0,0,1) 0%,rgba(51,51,51,1) 100%); /* IE10+ */
	background: linear-gradient(to bottom,  rgba(0,0,0,1) 0%,rgba(51,51,51,1) 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#000000', endColorstr='#333333',GradientType=0 ); /* IE6-8 */
	
}

div.content_localidade div.box_text_cities span
{
	padding-left: 24px; background: url('/img/btn_select_cities.png') left center no-repeat; padding-bottom: 2px;

}
div.content_localidade div.cities ul li a
{
	color: #000;
}

div.content_localidade div.cities ul li a:hover
{
	color: #ccc;
}

div.content_localidade div.headline
{
	color: #FFF;
	font-size: 40px;
	width: 380px;
	letter-spacing: 1px;
	line-height: 120%;
	float: right;
	padding-top: 70px;
	margin-right: 50px;
	background: transparent url("/img/index_arrow.png") right 20px no-repeat;
}
div.content_localidade div.headline span
{
	color: #FF9900;
	font-size: 50px;
}
</style>
